---
title: "Applied Statistics (M358K)"
output: 
  html_document
---

<style>
  hr {
      position: relative; 
            top: 20px; 
            border: none; 
            height: 2px; 
            background: black; 
            margin-bottom: 50px; 
  }
</style>
  
---

**Important/interesting external links**

[VSauce: What is random?](https://www.youtube.com/watch?v=9rIy0xY99a0)

[Veritasium: What is NOT random?](https://youtu.be/sMb00lz-IfE)

[A good
read](http://www.amazon.com/Cartoon-Guide-Statistics-Larry-Gonick/dp/0062731025/ref=sr_1_1?ie=UTF8&qid=1453216179&sr=8-1&keywords=cartoon+guide+to+statistics)

[R (main website)](https://www.r-project.org/)

[RStudio (main website)](https://rstudio.com/)

[Working directory in `R`](https://r-coder.com/working-directory-r/)

[Open course statistics book](https://www.openintro.org/book/os/)

---

**Class 1: August 21st**<br>
Orientation. <br>

[A role model](pics/bilbo.jpeg)

[The first-day handout (unique: 55635; 11am-11:50am)](syllabus/syllabus-55635.pdf)

[The first-day handout (unique: 55640; 1pm-1:50pm)](syllabus/syllabus-55640.pdf)

[To-Do](notes/m358k-to-do.pdf) 

[Open course video](https://youtu.be/rG-SLQ2uF8U): The definition of probability and first properties

[Open course video](https://youtu.be/HxEz4ZHUY5Y): Conditional probability. Probability trees. Bayes theorem. 

[Homework Instructions](instructions/m358k-hw-instructions.html) -- if in doubt, read and understand all of this before you work on your homework/project

[Homework Template](code/homework-template.Rmd) -- this is an optional template you can use to complete your homework assignments and projects 

[Homework #1](hw/m358k-hw-one.pdf) -- due on **Friday, September 1st**

[Homework #1](code/m358k-hw-one-probs.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your homework assignment 

---

**Class 2: August 23rd**<br>
Setting up R and RStudio. Basics of `R`. `R`-scripts.<br>

[The instructions slideshow](instructions/m358k-R-instructions.html)

[The basic R slideshow](instructions/m358k-basic-R.html)

[Console printout](notes/console.txt)

[The R-script from class](code/first-script.R)

[The basic R "cheatsheet"](https://raw.githubusercontent.com/rstudio/cheatsheets/master/base-r.pdf)

---

**Class 3: August 25th**<br>
R-notebooks. Functions in R. `If ... else` in R.<br>

[Warm-up worksheet #1](ww/m358k-ww1-common-sense.pdf): Problems 

[Warm-up worksheet #1](ww/m358k-ww1-common-sense-solns.pdf): Solutions

[The R-notebook from class](code/first-notebook.Rmd)

[A tutorial on functions in R](https://www.tutorialspoint.com/r/r_functions.htm)

[If ... else](https://www.datamentor.io/r-programming/if-else-statement/)

[The R-script from class](code/toy-ftions-if-inclass.R)

[Working directory in `R`](https://r-coder.com/working-directory-r/)

[Project #1: Part #1](projects/m358k-team-contract.docx) -- due on **Monday, September 11th**

[Project #1: Part #2](projects/m358k-project-one.pdf) -- due on **Monday, September 11th**

[Project #1: Part #2](code/m358k-project-one.Rmd) -- the Rmd file for those who are interested

---

**Class 4: August 28th**<br>
Review of discrete random variables.<br>

[Warm-up worksheet #2](code/m358k-ww2-basic-r.Rmd): Problems 

[Warm-up worksheet #2](code/m358k-ww2-basic-r-solns.Rmd): Solutions

Bernoulli and binomial <span style="color: purple;">**(Section 4.3)**</span>.<br>

[Wikipedia: Bernoulli trials](https://en.wikipedia.org/wiki/Bernoulli_trial) -- if you are interested 

[Wikipedia: Jacob Bernoulli](https://en.wikipedia.org/wiki/Jacob_Bernoulli) -- if you are interested  

[Class notes](notes/m358k-aug-28-2023.pdf) 

---

**Class 5: August 30th**<br> 
Bernoulli and binomial [cont'd] <span style="color: purple;">**(Section 4.3)**</span>.<br>

[Wikipedia: The Binomial Distribution](https://en.wikipedia.org/wiki/Binomial_distribution) -- if you are interested

[Mathematica demonstration: The Binomial Distribution](http://demonstrations.wolfram.com/BinomialDistribution/) 

[Open course video](https://youtu.be/tKmyzhvgudw): A review of the binomial distribution

[Class notes](notes/m358k-aug-30-2023.pdf) 

[Homework #2](hw/m358k-hw-two.pdf) -- due on **Friday, September 8th, 2023**

[Homework #2](code/m358k-hw-two.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your homework assignment 

Simulations of random variables. Plots. Histograms. <span style="color: purple;">**(Section 2.1.3)**</span><br>

[Wikipedia: Random number generation](https://en.wikipedia.org/wiki/Random_number_generation)

[Wikipedia: Mersenne twister](https://en.wikipedia.org/wiki/Mersenne_Twister)

[An atmospheric RNG](https://www.random.org/)

[Setting a seed in `R`](https://r-coder.com/set-seed-r/)

[The R-script from class](code/binomial-demo.R)

[Homework #3](hw/m358k-hw-three.pdf) -- due on **Friday, September 15th, 2023**

[Homework #3](code/m358k-hw-three.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your homework 

[Project #2](projects/m358k-project-two.pdf) -- **due on Monday, September 25h** 

[Project #2](code/m358k-project-two.Rmd) -- this is the Rmd file which you are more than welcome to use to neatly complete your project 

---

**Class 6: September 1st**<br>
Warm-up.<br>

[Warm-up worksheet #3](ww/m358k-ww3-sims-probs.Rmd): Problems

[Warm-up worksheet #3](code/m358k-ww3-sims-solns.Rmd): Solutions

[The R-script from class](code/war.R)

What is statistics? 
<span style="color: purple;">**(Sections 1.2.1, 1.2.2)**</span><br>

[Class notes](notes/m358k-sept-01-2023.pdf) 

[Open course video](https://youtu.be/Mjif8PTgzUs): Data basics

Data presentation [graphical]
<span style="color: purple;">**(Sections 2.2.1, 2.2.5)**</span><br>

[Open course video](https://youtu.be/7NhNeADL8fA): Exploring categorical data

---

**Class 7: September 6th**<br> 
Fitting.<br>

[Class notes](notes/m358k-sept-06-2023.pdf) 

Data presentation [more on graphical; numerical]
<span style="color: purple;">**(Sections 2.1.2, 2.1.3, 2.1.4)**</span>\

[Data](data/pie-survey.csv): Favorite pies

R notebook [cat-data.Rmd](code/cat-data.Rmd)

[Data](data/antibiotics.csv): Pre-existing conditions data - courtesy of the *Open Course Statistics*

[Extra credit #1](quizzes/m358k-quiz1-eda.pdf) -- **due on Wednesday, September 27th**; you can use the points earned towards your homework scores

[Extra credit #1](code/m358k-quiz1-eda.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your quiz; you will **not** be able to knit this file as is unless you comment out or delete the `R`-chunk which inserts the picture 

[Data](data/titanic.csv): Simplified Titanic data - courtesy of the *Journal of Statistics Education* 

R notebook [titanic.Rmd](code/titanic.Rmd)

R notebook [titanic-in-class.Rmd](code/titanic-in-class.Rmd) as amended in class 

[xkcd](https://xkcd.com/1140/) 

[Florence Nightingale](http://thisisstatistics.org/florence-nightingale-the-lady-with-the-data/) 

[Wikipedia: Mean household income](https://en.wikipedia.org/wiki/Household_income_in_the_United_States#Mean_household_income) 

[Graph: US Household Income Distribution](pics/m358k-hh-inc-dist-2015.pdf)

Here is a list of fun sites which make charts: [Infogram](https://infogram.com/), [FastCharts](https://fastcharts.io/), [Flourish](https://flourish.studio/), 
[Datawrapper](https://www.datawrapper.de/)

---

**Class 8: September 8th**<br>
Median. Quartiles. <span style="color: purple;">**(Sections 2.1.5, 2.1.6, 2.1.1)**</span><br>

[Slides](notes/m358k-2.1-examining-numerical-data.pdf) - **Courtesy of Open Course Statistics**

R script [invented-data.R](code/invented-data.R) from class

[Return values from boxplot](https://r-coder.com/boxplot-r/#Return_values_from_boxplot)

[ProPublica](https://projects.propublica.org/climate-migration/): New Climate Maps Show a Transformed United States

[Data](data/cafedata.csv): Student-run cafe - courtesy of the *Journal of Statistics Education* 

[Homework #4](hw/m358k-hw-four.pdf) -- due on **Friday, September 22nd, 2023**

[Homework #4](code/m358k-hw-four.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your homework; you will **not** be able to knit this file as is unless you comment out or delete the `R`-chunk which inserts the picture

---

**Class 9: September 11th**<br>
Scatterplots  <span style="color: purple;">**(Section 1.2.3)**</span>.<br>

[Data](data/diamond.csv): Carats vs. dollars - courtesy of the *Journal of Statistics Education* 

`R`-script [diamond-scatterplot.R](code/diamond-scatterplot.R)

[On plotting scatterplots in R](https://youtu.be/X66b-Jbi15w) - this is a demo in R by yours truly on how to draw scatterplots; feel free to start at 2:35 and watch at twice the speed  

Adding [legends](http://www.sthda.com/english/wiki/add-legends-to-plots-in-r-software-the-easiest-way) to your `R` plots

[Duke gpa](data/gpa.csv) - courtesy of OpenCourse Statistics

[The R-notebook for class](code/m358k-gpa-probs.Rmd)

[The R-notebook from class](code/m358k-gpa-in-class.Rmd) - I added a few features to our work in class, so check it out

[Gapminder](https://www.gapminder.org/answers/how-does-income-relate-to-life-expectancy/): How Does Income Relate to Life Expectancy?

[Homework #5](hw/m358k-hw-five.pdf) -- due on **Friday, September 29th, 2023**

---

**Class 10: September 13th**<br>
Sampling principles and strategies <span style="color: purple;">**(Section 1.3)**</span><br>

[Slides](notes/m358k-1.3-sampling.pdf) - **Courtesy of Open Course Statistics**

[Problem Set #1](exams/m358k-ps-one-sampling.pdf) - **problems**

[Problem Set #1](exams/m358k-ps-one-sampling-solns.pdf) - **solutions**

[In-Term One Topics](exams/m358k-one-topics.pdf) 

[Practice for In-Term One](exams/m358k-one-sample-probs.pdf) - **Problems**

[Practice for In-Term One](exams/m358k-one-sample-solns.pdf) - **Solutions**

---

**Class 11: September 15th**<br>
Randomized response.<br>

[James Grime on randomized response](https://youtu.be/nwJ0qY_rP0A) 

[Wikipedia: Randomized response](https://en.wikipedia.org/wiki/Randomized_response) 

[Problem Set #2](exams/m358k-ps-two-rand-resp.pdf) - **problems**

[Problem Set #2](exams/m358k-ps-two-rand-resp-solns.pdf) - **solutions**

[Class notes](notes/m358k-sept-15-2023.pdf) 

---

**Class 12: September 18th**<br>
Experiments <span style="color: purple;">**(Section 1.4)**</span><br>

[Open Course Video](https://youtu.be/g7JGe_ykB3I)

[Slides](notes/m358k-1.4-experiments.pdf) - **Courtesy of Open Course Statistics**

[Problem Set #3](exams/m358k-ps-three-collecting-data.pdf) - **problems**

[Problem Set #3](exams/m358k-ps-three-collecting-data-solns.pdf) - **solutions**

[Class Notes](notes/m358k-sept-18-2023.pdf)

[A historical example](https://helix.northwestern.edu/blog/2010/02/when-science-goes-wrong) 

**Suggested textbook problems** (for after you are done with all the homework): <span style="color: purple;">**1.19, 1.20, 1.23, 1.26, 1.27, 1.28, 2.11, 2.13, 3.9, 3.10, 3.13, 3.19**</span><br>

[Project #3](projects/m358k-project-three.pdf) -- **due on Monday, October 9th** 

[Project #3](code/m358k-project-three.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your quiz 

[Follow up on the "Experiment experiment"](https://www.npr.org/sections/health-shots/2018/08/27/642218377/in-psychology-and-other-social-sciences-many-studies-fail-the-reproducibility-te/)

[Andrew Gelman on the "replication crisis"](http://andrewgelman.com/2016/03/03/more-on-replication-crisis/) 


---

**Class 13: September 20th**<br>
<span style="color: red;">**In-Term One**</span><br>

[In-Term One](exams/m358k-one-solns.pdf) - **solutions**

---

**Class 14: September 22nd**<br>
Review of continuous distributions.<br>

[Class notes](notes/m358k-sept-22-2023.pdf) 

[Extra-Credit Quiz #3](quizzes/m358k-ec-quiz3.pdf) -- **due on Wednesday, October 4th**

[Extra-Credit Quiz #3](code/m358k-ec-quiz3.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your quiz 

---

**Class 15: September 25th**<br>
Statistical inference. Statistics and the sampling distribution.<br>

R notebook [Odin.Rmd](code/Odin.Rmd)

[Sample versus Theoretical Distribution](http://demonstrations.wolfram.com/SampleVersusTheoreticalDistribution/){.demonstrationHyperlink} from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Joe Bolte 

Point estimates and sampling variability <span style="color: purple;">**(Section 5.1)**</span><br>

[Slides](notes/m358k-5.1-point-estimates-and-sampling-variability.pdf) - **Courtesy of Open Course Statistics**

R notebook [prop.Rmd](code/prop.Rmd)

[Problem Set #4](problem-sets/m358k-ps-four.pdf) - **problems**

[Problem Set #4](problem-sets/m358k-ps-four-solns.pdf) - **solutions**

---

**Class 16: September 27th**<br>
The normal distribution [review] <span style="color: purple;">**(Section 4.1, Appendix C.1)**</span><br>

[Class notes](notes/m358k-sept-27-2023.pdf) 

[The R-script from class](code/normal.R)

[Standard Normal Distribution Areas](http://demonstrations.wolfram.com/StandardNormalDistributionAreas/){.demonstrationHyperlink} from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Ian McLeod 

[The Normal Distribution](http://demonstrations.wolfram.com/TheNormalDistribution/) from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Ian McLeod 

[Area of a Normal Distribution](http://demonstrations.wolfram.com/AreaOfANormalDistribution/){.demonstrationHyperlink} from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Eric Schulz 

[Standard normal table](notes/std-normal-table.pdf)

[Slides](notes/m358k-4.1-normal-distribution.pdf) - **Courtesy of Open Course Statistics**

[Wikipedia: Six sigma](https://en.wikipedia.org/wiki/Six_Sigma)

[How to shade in R](http://www.alisonsinclair.ca/2011/03/shading-between-curves-in-r/) 

[Homework #6](hw/m358k-hw-six.pdf) -- due on **Friday, October 6th**

[Homework #6](code/m358k-hw-six.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your homework assignment 

[Mystery Data](data/mystery-data.csv): this data set is necessary for *Project #4*

[Bitcoin Data](data/bitcoin.csv): this data set is necessary for *Project #4*

[Project #4](projects/m358k-project-four.pdf) -- **due on Monday, October 25th** 

[Project #4](code/m358k-project-four.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your project 

[%in% in `R`](https://www.marsja.se/how-to-use-in-in-r/)


---

**Class 17: September 29th**<br>
More on the normal distribution.<br>

[Problem Set #5](problem-sets/m358k-ps-five-normal.pdf) -- **problems**

<!--
[Problem Set #5](problem-sets/m358k-ps-five-normal-solns.pdf) -- **solutions**

[Class notes](notes/m358k-oct-03-2022.pdf) 
-->

---

**Class 18: October 2nd**<br>
The normal approximation to the binomial [review] <span style="color: purple;">**(Sections 4.3.2 and 4.3.3)**</span>.<br>

[Problem Set #6](problem-sets/m358k-ps-six-dML.pdf) -- **problems**

<!--
[Class notes](notes/m358k-oct-05-2022.pdf) 

[The R-script from class](code/dML.R)


[Problem Set #6](problem-sets/m358k-ps-six-dML-solns.pdf) -- **solutions**

-->

[Mathematica demonstration](http://demonstrations.wolfram.com/IllustratingTheCentralLimitTheoremWithSumsOfBernoulliRandomV/): The Normal Approximation to the Binomial Distribution

[Open Course Video](https://www.youtube.com/watch?v=VvksxAZAlrQ&list=PLkIselvEzpM6V9h55s0l9Kzivih9BUWeW): Normal approximation to the binomial


---

**Class 19: October 4th**<br>
The Central Limit Theorem [review] <span style="color: purple;">**(Sections 5.1.3 and 7.1.1)**</span>.<br>

[Problem Set #7](problem-sets/m358k-ps-seven-CLT.pdf) -- **problems**

<!--
[Class notes](notes/m358k-oct-07-2022.pdf)

[Wikipedia](https://en.wikipedia.org/wiki/Gamma_distribution): On the **gamma distribution**

[The R-script from class](code/clt-in-class.R)

[Problem Set #7](problem-sets/m358k-ps-seven-CLT-solns.pdf) -- **solutions**

[Homework #7](hw/m358k-hw-seven.pdf) -- due on **Friday, October 21st, 2022**

[Homework #7](code/m358k-hw-seven.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your homework assignment 


---

**Class 20: October 7th**<br>
Sample mean (the normal case).<br>

[Class notes](notes/m358k-oct-10-2022.pdf) 

[Problem Set #8](problem-sets/m358k-ps-eight-normal-sample.pdf) -- **problems**

[Problem Set #8](problem-sets/m358k-ps-eight-normal-sample-solns.pdf) -- **solutions**

[Quiz #7](quizzes/m358k-quiz-seven.pdf) -- **due on Friday, October 8th**

[Quiz #7](code/m358k-quiz-seven.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your quiz 

--- 

**Class 21: October 10th**<br>
Confidence intervals (the normal case). <br>

[Class notes](notes/m358k-oct-12-2022.pdf) 

[Class notes](notes/m358k-oct-14-2022.pdf) 

R notebook [normal-conf-int.Rmd](code/normal-conf-int.Rmd)

Shiny: [Confidence intervals](https://milica-cudina.shinyapps.io/Coverage/)

[Problem Set #9](problem-sets/m358k-ps-nine-normal-conf-int.pdf) -- **problems**

[Problem Set #9](problem-sets/m358k-ps-nine-normal-conf-int-solns.pdf) -- **solutions**

[Homework #7](hw/m358k-hw-seven-solns.pdf) -- **solutions**

[Quiz #8](quizzes/m358k-quiz-eight-normal-conf-int.pdf) -- **due on Friday, October 15th**

[Homework #8](hw/m358k-hw-eight.pdf) -- due on **Friday, October 28th, 2022**

[Homework #8](code/m358k-hw-eight.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your homework assignment 

---

**Class 22: October 12th**<br>
Principles of hypothesis testing. The $p−$value.<br>

[Class notes](notes/m358k-oct-15-2021.pdf) 

[Quiz #8](quizzes/m358k-quiz-eight-normal-conf-int-solns.pdf) -- **solutions**

[In-Term Two Topics](exams/m358k-two-topics.pdf) 

[Practice for In-Term Two](exams/m358k-two-sample-solns.pdf) - **Problems**

[Practice for In-Term Two](exams/m358k-two-sample-probs.pdf) - **Solutions**

---

**Class 23: October 14th**<br>
More on hypothesis testing in the normal case. 

[Class notes](notes/m358k-oct-18-2021.pdf) 

[Problem Set #10](problem-sets/m358k-ps-ten-hypothesis-test-p-value-mean.pdf) -- **problems**

[Problem Set #10](problem-sets/m358k-ps-ten-hypothesis-test-p-value-mean.pdf) -- **solutions**

[Extra-Credit Quiz #2](quizzes/m358k-quiz2-normal-hyp-test.pdf) -- **due on Wednesday, November 2nd, 2022**

[Extra-Credit Quiz #3](quizzes/m358k-quiz3-more-hyp-test.pdf) -- **due on Wednesday, November 9th, 2022**

[Mock In-Term Two](exams/m358k-two-mock-probs.pdf) - **Problems**

[Mock In-Term Two](exams/m358k-two-mock-solns.pdf) - **Solutions**

---

**Class 24: October 17th**<br>
The reasoning of tests of significance. Inference as a decision.<br>

[Class notes](notes/m358k-oct-20-2021.pdf) 

[$p-$hacking is bad](https://www.popularmechanics.com/science/math/a40971517/p-value-statistics-fragility-index/)

---

**Class 25: October 19th**<br>
<span style="color: red;">**In-Term Two**</span><br>

[In-Term Two](exams/m358k-two-solns.pdf) - **Solutions**

---

**Class 26: October 21st**<br>
Hypothesis-testing practice (the normal case).<br>

[Class notes](notes/m358k-oct-22-2021-abridged.pdf) 

[Problem Set #11](problem-sets/m358k-ps-eleven-sign-test-mean.pdf) -- **problems** 

[Problem Set #11](problem-sets/m358k-ps-eleven-sign-test-mean-solns.pdf) -- **solutions** 

An [article](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002106) on **p-hacking** in biology

A [blog post](https://fivethirtyeight.com/features/science-isnt-broken/#part1) on **p-hacking** with an interactive component

[Problem Set #12](problem-sets/m358k-ps-twelve-normal-hyp-test.pdf) -- **problems** 

[Problem Set #12](problem-sets/m358k-ps-twelve-normal-hyp-test-solns.pdf) -- **solutions** 

[Quiz #9](quizzes/m358k-quiz-nine-normal-hyp-test-solns.pdf) -- **solutions**

---

**Class 27: October 24th**<br>
Types of errors.<br>

[Errors](pics/pregnant.jpg)

[Class notes](notes/m358k-oct-29-2022.pdf)

[Problem Set #13](problem-sets/m358k-ps-thirteen-errors.pdf) -- **problems** 

[Problem Set #13](problem-sets/m358k-ps-thirteen-errors-solns.pdf) -- **solutions** 

[R-bloggers](https://www.r-bloggers.com/2021/06/qq-plots-in-r-quantile-quantile-plots-quick-start-guide/): QQ-plots in `R`

[Data](data/temperatures-heart.csv): this data set is necessary for *Project #5*

[Project #5](projects/m358k-project5-probs.pdf) -- **due on Monday, November 15th** 

[Project #5](code/m358k-project-five-probs.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your project 

---

**Class 28: October 26th**<br>
Power of test (the normal case).<br>

[Power of test](pics/power.png)

[Class notes](notes/m358k-oct-31-2022.pdf)

[Homework #9](hw/m358k-hw-nine.pdf) -- due on **Friday, November 4th**

[Homework #9](code/m358k-hw-nine.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your homework assignment 

[Extra class notes](notes/m358k-oct-29-2021.pdf)

[Problem Set #14](problem-sets/m358k-ps-fourteen-power-of-test.pdf) -- **problems** 

[Problem Set #14](problem-sets/m358k-ps-fourteen-power-of-test-solns.pdf) -- **solutions** 

[Quiz #10](quizzes/m358k-quiz-ten-more-hyp-test-solns.pdf) -- **solutions**

---

**Class 29: October 28th**<br>
The sampling distribution for *counts* and  *proportions*. Confidence intervals 
<span style="color: purple;">**(Sections 6.1.1, 6.1.2, and 6.1.5)**</span><br>

[Open course video](https://youtu.be/_iFAZgpWsx0): Statistical inference for proportions.

[Class notes](notes/m358k-nov-02-2022.pdf)

[Problem set #15](problem-sets/m358k-ps-fifteen-single-prop-conf-int.pdf) -- **problems**

[Problem set #15](problem-sets/m358k-ps-fifteen-single-prop-conf-int-solns.pdf) -- **solutions**

[Quiz #11](quizzes/m358k-quiz-eleven-one-prop-conf-int.pdf) -- **due on Friday, November 5th, 2021**

[Homework #10](hw/m358k-hw-ten.pdf) -- due on **Friday, November 11th**

[Homework #10](code/m358k-hw-ten.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your homework assignment 

---

**Class 30: October 31st**<br>
Hypothesis testing for a  *proportion* 
<span style="color: purple;">**(Section 6.1.3)**</span><br>

[Class notes](notes/m358k-nov-04-2022.pdf)

[Problem set #16](problem-sets/m358k-ps-sixteen-single-prop-hyp-test.pdf) -- **problems**

[Problem set #16](problem-sets/m358k-ps-sixteen-single-prop-hyp-test-solns.pdf) -- **solutions**

---

**Class 31: November 2nd**<br>
Comparing two proportions <span style="color: purple;">**(Sections 6.2.1, 6.2.2, 6.2.3, 6.2.5)**</span><br>

[Class notes](notes/m358k-nov-07-2022.pdf)

[Complete class notes](notes/m358k-nov-05-2021.pdf)

[Problem set #17](problem-sets/m358k-ps-seventeen-two-props.pdf) -- **problems**

[Problem set #17](problem-sets/m358k-ps-seventeen-two-props-solns.pdf) -- **solutions**

[Quiz #11](quizzes/m358k-quiz-eleven-one-prop-conf-int-solns.pdf) -- **solutions**

[Quiz #12](quizzes/m358k-quiz-twelve-prop-hyp-test.pdf) -- **due on Friday, November 12th, 2020**

[Homework #11](hw/m358k-hw-eleven.pdf) -- due on **Friday, November 18th**

[Homework #11](code/m358k-hw-eleven.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your homework assignment 

[Extra-Credit Quiz #2](quizzes/m358k-quiz2-normal-hyp-test-solns.pdf) -- **solutions**

---

**Class 32: November 4th**<br>
The $\chi^2-$ distribution <span style="color: purple;">**(Sections 6.3.3, C.3)**</span><br>

[Class notes](notes/m358k-nov-11-2022.pdf)

[$\chi^2-$table](notes/chi-squared-table.pdf)

[A better $\chi^2-$table](notes/chi-squared-table-better.pdf)

[Mathematica demonstration: The Chi-Squared Distribution](http://demonstrations.wolfram.com/TheChiSquaredDistribution/)

[Mathematica demonstration: Tail Areas under the Chi-Squared Distribution](https://demonstrations.wolfram.com/TailAreasUnderChiSquaredDistributions/#embed)

---

**Class 33: November 7th**<br>
Goodness of fit <span style="color: purple;">**(Sections 6.3.1, 6.3.2, 6.3.4)**</span><br> 

[Open course video](https://youtu.be/Uk36WGxujkc): Goodness of fit.

[Class notes](notes/m358k-nov-11-2021.pdf)

[Problem set #18](problem-sets/m358k-ps-eighteen-goodness-of-fit.pdf) -- **problems**

[Problem set #18](problem-sets/m358k-ps-eighteen-goodness-of-fit-solns.pdf) -- **solutions**

---

**Class 34: November 9th**<br>
Analysis of two-way tables. 

[James Grime on the Simpson's paradox](https://youtu.be/wgLUDw8eLB4) 

Chi-squared test of independence <span style="color: purple;">**(Section 6.4)**</span><br>

[Class notes](notes/m358k-nov-12-2021.pdf)

[Slides](notes/m358k-6.4-chi-squared-test-independence.pdf) - **Courtesy of Open Course Statistics**

[R-code: On-line courses or not?](code/chi-square.R): An example on how to do the $\chi^2-$test of independence in `R`

[Quiz #13](quizzes/m358k-quiz-thirteen-goodness-of-fit.pdf) -- **due on Friday, November 19th, 2021**

[Extra-Credit Quiz #3](quizzes/m358k-quiz3-more-hyp-test-solns.pdf) -- **solutions**

---

**Class 36: November 11th**<br>
$\chi^2-$connections to normal samples.<br>

[Statistics Associated with Normal Samples](http://demonstrations.wolfram.com/StatisticsAssociatedWithNormalSamples/){.demonstrationHyperlink} from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Pierre-Emmanuel Robert 

[Quiz #14](quizzes/m358k-quiz-fourteen-chi-squared.pdf) -- **due on Friday, December 3rd, 2021**

The $t-$distribution <span style="color: purple;">**(Sections 7.1.3 and C.2)**</span>.<br>

[Wikipedia](https://en.wikipedia.org/wiki/William_Sealy_Gosset): William Sealy Gosset 

[Mathematica demonstration](http://demonstrations.wolfram.com/StudentsTDistribution/): The Student's t-distribution 

[Class notes](notes/m358k-nov-15-2021.pdf)

[Data](data/euro-weights.csv): this data set is necessary for *Project #6*

[Project #6](projects/m358k-project-six.pdf) -- **due on Monday, December 5th** 

[Project #6](code/m358k-project-six.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your project 

[Wikipedia](https://en.wikipedia.org/wiki/Fisher%27s_exact_test): Fisher's exact test 

---

**Class 36: November 14th**<br>
The confidence interval for the population mean <span style="color: purple;">**(Section 7.1.1, 7.1.2, 7.1.4)**</span><br>

[Class notes](notes/m358k-nov-17-2021.pdf)

[R-code](code/dobson-ozone.R): Normality check for Dobson

[R-code](code/t-conf-int.R): Confidence intervals with `t.test`

---

**Class 37: November 16th**<br>
The t-test <span style="color: purple;">**(Section 7.1.5)**</span><br>

[Class notes](notes/m358k-nov-19-2021.pdf)

[Slides](notes/m358k-7.1-one-sample-means-with-the-t-distribution.pdf) - **Courtesy of Open Course Statistics**

[Quiz #13](quizzes/m358k-quiz-thirteen-goodness-of-fit-solns.pdf) -- **solutions**

[In-Term Three Topics](exams/m358k-three-topics.pdf) 

[Practice for In-Term Three](exams/m358k-three-sample.pdf) - **problems**

[Practice for In-Term Three](exams/m358k-three-sample-solns.pdf) - **solutions**

---

**Class 38: November 18th**<br>
t-procedures practice.<br>

[Class notes](notes/m358k-nov-22-2021.pdf)

[Problem set #19](problem-sets/m358k-ps-nineteen-t-procedures.pdf) -- **problems**

[Problem set #19](problem-sets/m358k-ps-nineteen-t-procedures-solns.pdf) -- **solutions**

Robustness of t-procedures (optional).

[Robustness of Student t in the One-Sample  Problem](http://demonstrations.wolfram.com/RobustnessOfStudentTInTheOneSampleProblem/){.demonstrationHyperlink} 
from the [Wolfram Demonstrations  Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Ian McLeod 

[The Royal Society of Chemistry on *robustness*](http://www.rsc.org/images/robust-statistics-technical-brief-6_tcm18-214850.pdf) 

Paired data <span style="color: purple;">**(Section 7.2)**</span><br>

[Slides](notes/m358k-7.2-paired-data.pdf) - **Courtesy of Open Course Statistics**

[Homework #12](hw/m358k-hw-twelve.pdf) -- due on **Friday, December 2nd**

[Homework #12](code/m358k-hw-twelve.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your homework assignment 

[The Final Project](projects/m358k-project-final.pdf) -- **due on Friday, December 9th** 

---

**Class 39: November 28th**<br>
Difference of two means <span style="color: purple;">**(Section 7.3)**</span><br>

[Class notes](notes/m358k-nov-29-2021.pdf)

[Slides](notes/m358k-7.3-difference-of-two-means.pdf) - **Courtesy of Open Course Statistics**

[Quiz #15](quizzes/m358k-quiz-fifteen-two-means.pdf) -- **due on Monday, December 6th for extra credit**

t-procedures [practice].<br>

[The R-script from class](code/t-test.R)

[Class notes](notes/m358k-dec-01-2021.pdf)

[Problem set #20](problem-sets/m358k-ps-twenty-two-means.pdf) -- **problems**

[Problem set #20](problem-sets/m358k-ps-twenty-two-means-solns.pdf) -- **solutions**

[Mock In-Term Three](exams/m358k-three-mock.pdf) - **Problems**

[Mock In-Term Three](exams/m358k-three-mock-solns.pdf) - **Solutions**


---

**Class 40: November 30th**<br>
<span style="color: red;">**In-Term Three**</span><br>

[In-Term Three](exams/m358k-three-solns.pdf) - **solutions**

---

**Class 41: December 2nd**<br> 
Correlation. Causation <span style="color: purple;">**(Section 8.1.4)**</span><br>

[xkcd](https://xkcd.com/552/): Correlation

[Class notes](notes/m358k-dec-03-2021.pdf)

[Visualizing Correlations](http://demonstrations.wolfram.com/VisualizingCorrelations/){.demonstrationHyperlink} from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Ian McLeod

[Anscombe Quartet](http://demonstrations.wolfram.com/AnscombeQuartet/){.demonstrationHyperlink} from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Ian McLeod 

[Datasaurus](https://cran.r-project.org/web/packages/datasauRus/vignettes/Datasaurus.html)

[Problem set #21](problem-sets/m358k-ps-twenty-one-corr-linear-transforms.pdf) -- **problems**

[Problem set #21](problem-sets/m358k-ps-twenty-one-corr-linear-transforms-solns.pdf) -- **solutions**

[Data](data/shoesize.csv): Shoe size and height - courtesy of the *Open Course Statistics*: this data set is necessary for *Quiz #16*

[Quiz #14](quizzes/m358k-quiz-fourteen-chi-squared-solns.pdf) -- **solutions**

[Quiz #16](quizzes/m358k-quiz-sixteen.pdf) -- **due on Monday, December 6th for extra credit**

[Quiz #16](code/m358k-quiz-sixteen.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your quiz 

---

**Class 42: December 5th**<br> 
Fitting a line. Residuals <span style="color: purple;">**(Sections 8.1.1, 8.1.2, 8.1.3)**</span><br>

[Slides](notes/m358k-8.1-line-fitting-residuals-correlation.pdf) - **Courtesy of Open Course Statistics**

[Class notes](notes/m358k-dec-06-2021.pdf)

Least-squares. Predictive statistical tools <span style="color: purple;">**(Section 8.2)**</span><br>

[Least squares with the mechanical analogue](http://www.physics.utah.edu/~belz/phys3719/lecture04.pdf) 

Simple linear regression.<br>

[Least Squares Criteria for the Least Squares Regression Line](http://demonstrations.wolfram.com/LeastSquaresCriteriaForTheLeastSquaresRegressionLine/){.demonstrationHyperlink} from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Mariel Maughan 

[Mean, Fitted-Value, Error, and Residual in Simple Linear Regression](http://demonstrations.wolfram.com/MeanFittedValueErrorAndResidualInSimpleLinearRegression/){.demonstrationHyperlink} from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Ian McLeod 

[R-code](code/simple-least-squares.R): Simple linear regression

[Regression toward the Mean](http://demonstrations.wolfram.com/RegressionTowardTheMean/){.demonstrationHyperlink} from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Ian McLeod

[Quiz #17](quizzes/m358k-quiz-seventeen-regression.pdf) -- **due on Monday, December 6th for extra credit**

Simple linear regression [cont'd].<br>

[R-code](code/slr-conf-ints.R): Confidence intervals

[Goodhart's Law](https://youtu.be/SwcK7NI_i98) on YouTube

---

[The Final Exam Topics](exams/m358k-final-topics.pdf) 

[The Final Exam Practice](exams/m358k-final-practice.pdf) -- **problems**

[The Final Exam Practice](exams/m358k-final-practice-solns.pdf) -- **solutions**

---

**Three interesting special topics**<br>

<span style="color: blue;">**Lady tasting tea.**</span><br>

[Wikipedia](https://en.wikipedia.org/wiki/Lady_tasting_tea): Lady tasting tea

R. Fisher: [Mathematics of a Lady Tasting Tea](pdf/m358k-lady-tasting-tea-original.pdf)

[Lady Tasting Coffee](http://sciencecases.lib.buffalo.edu/cs/files/2-lady_tasting_tea.pdf): A case study in experimental design

<span style="color: blue;">**The foster-twins study.**</span><br>

[Wikipedia](https://en.wikipedia.org/wiki/Cyril_Burt): Cyril Burt

<span style="color: blue;">**The German tank problem.**</span><br>

[Wikipedia](https://en.wikipedia.org/wiki/German_tank_problem): The German tank problem

---

<!--
[Mock In-Term One](exams/m358k-mock-one-probs.pdf) - **Problems**

[Mock In-Term One](exams/m358k-mock-one.pdf) - **Solutions**

---


[In-term exam #3](exams/m358k-in-term-three-battle-plan.pdf): Battle plan

[In-Term Three](exams/m358k-three.pdf) - **Solutions**

---

<!-- [Quiz \#6](m358k-quiz-six-clt.pdf) \-- Solutions -->

<!-- F-distribution.\ -->

<!-- [Wikipedia: The -->
<!-- F-distribution](https://en.wikipedia.org/wiki/F-distribution) -->

<!-- [The F-Ratio -->
<!-- Distribution](http://demonstrations.wolfram.com/TheFRatioDistribution/){.demonstrationHyperlink} -->
<!-- from the [Wolfram Demonstrations -->
<!-- Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by -->
<!-- Chris Boucher -->

<!-- F-test\ -->

<!-- [R-code: Weight-loss campaign](weights.R) -->

<!-- [Class notes](m358k-apr-21.pdf) -->

<!-- Simple linear regression \[cont\'d\].\ -->

<!-- [Open-source statistics -->
<!-- slides](https://www.openintro.org/stat/slides.php) -->

<!-- The coefficient of determination.\ -->

<!-- Confidence intervals for coefficients.\ -->


<!-- Confidence intervals for mean response.\ -->
<!-- Prediction intervals.\ -->

<!-- ANOVA for regression.\ -->

<!-- [xkcd: Twitter timeline height](https://what-if.xkcd.com/65/) -->









