---
title: "Quiz #12"
author: "Milica Cudina"
date: "`r Sys.Date()`"
output: pdf_document
---
<!-- The author of this template is Dr. Gordan Zitkovic.-->
<!-- The code chunk below contains some settings that will  -->
<!-- make your R code look better in the output pdf file.  -->
<!-- If you are curious about what each option below does, -->
<!-- go to https://yihui.org/knitr/options/ -->
<!-- If not, feel free to disregard everything ...  -->
```{r echo=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.align="center",
  fig.pos="t",
  fig.width=12,
  strip.white = TRUE
)
```
<!-- ... down to here. -->

# Simulations
## Problem 1.  
Consider the following two-step experiment. First you draw a simulated value from a Bernoulli(p=1/3). If the drawn value from the Bernoulli equals $0$, then you draw a simulated value from $Gamma(\alpha=2,\theta=5)$. On the other hand, if the drawn value from the Bernoulli equals $1$, then you draw a simulated value from $Gamma(\alpha=10,\theta=20)$

**(10 points)** Repeat the above two-step experiment $10000$ times and draw the histogram of the simulated values. 


**(2 points)**
Find the theoretical mean of the above distribution and compare it to the mean of the simulated values. 


**(3 points)**
Find the theoretical probability that the above random variable exceeds $100$. It's acceptable to use the `pgamma` command. Compare it to the proportion of the simulated values exceeding $100$.


