---
title: "Probability (M362K)"
output: html_document
---

<style>
  hr {
      position: relative; 
            top: 20px; 
            border: none; 
            height: 2px; 
            background: black; 
            margin-bottom: 50px; 
  }
</style>

---

**Important external links**

[Cornell Notes](http://lsc.cornell.edu/how-to-study/taking-notes/cornell-note-taking-system/)

---

**Class 1: January 17th**<br>
Orientation. <br>

[A role model](pics/bilbo.jpeg)

[First-Day Handout](syllabus/syllabus-53850.pdf): Unique 53850 (1pm)

[First-Day Handout](syllabus/syllabus-53855.pdf): Unique 53855 (2pm)

---

**Class 2: January 19th**<br>
Equally likely outcomes <span style="color: purple;">**(Section 1.1)**</span>.<br>

[Class notes](notes/m362k-jan-19-2024.pdf)

[Homework #1](hw/m362k-hw1.pdf) -- **due on Friday, January 26th**

---

**Class 3: January 22nd**<br>
Distributions <span style="color: purple;">**(Section 1.3)**</span>.<br>

[Wikipedia](https://en.wikibooks.org/wiki/Set_Theory/Sets): Set notation

[Class notes](notes/m362k-jan-22-2024.pdf)

[The R-script from class](code/frequencies.R): Long-term proportions

---

**Class 4: January 24th**<br>
Definition of *probability* <span style="color: purple;">**(Section 1.3)**</span>.<br>

[Class notes](notes/m362k-jan-24-2024.pdf)

---

**Class 5: January 26th**<br>
More on probability. Binomial coefficients.<br>

[Wikipedia](https://en.wikipedia.org/wiki/Standard_52-card_deck): Standard $52-$ card deck

[Class notes](notes/m362k-jan-26-2024.pdf)

---

**Class 6: January 29th**<br>
De Méré's paradox. Even more on probability.<br>

[Wikipedia](https://www.proofwiki.org/wiki/De_Méré's_Paradox): De Méré's paradox.

[Class notes](notes/m362k-jan-29-2024.pdf)

[The R-script from class](code/loaded-tetrahedron-in-class-too.R): A loaded tetrahedron with histograms and bar plots 

---

**Class 7: January 31st**<br>
Even even more on probability.<br>

[Class notes](notes/m362k-jan-31-2024.pdf)

[Letter frequencies in English](https://www3.nd.edu/~busiforc/handouts/cryptography/letterfrequencies.html)

**(Enrichment material)** [MCMC Revolution](https://math.uchicago.edu/~shmuel/Network-course-readings/MCMCRev.pdf) by legendary Persi Diaconis

---

**Class 8: February 2nd**<br>
Conditional probability and the multiplication formula <span style="color: purple;">**(Section 1.4)**</span>.<br>

[Wikipedia](https://en.wikipedia.org/wiki/Groundhog_Day): Groundhog day 

[Problem Set #1](problem-sets/m362k-ps1-cond-prob-ind-probs.pdf): **Problems**

[Class notes](notes/m362k-feb-02-2024.pdf)

[Wikipedia](https://en.wikipedia.org/wiki/Monty_Hall_problem): The Monty Hall problem

[Homework #2](hw/m362k-hw2-probability-probs.pdf) -- **due on Friday, February 9th**

---

**Class 9: February 5th**<br>
Independence and probability trees <span style="color: purple;">**(Section 1.4)**</span>.<br>

[Problem Set #1](problem-sets/m362k-ps1-cond-prob-ind-solns.pdf): **Solutions**

Bayes' rule <span style="color: purple;">**(Section 1.5)**</span>.<br>

[Class notes](notes/m362k-feb-05-2024.pdf)

---

**Class 10: February 7th**<br>
More on the Bayes rule <span style="color: purple;">**(Section 1.5)**</span>.<br>

[Class notes](notes/m362k-feb-07-2024.pdf)

[In-Term One](exams/m362k-one-topics.pdf): Topics

[Practice for In-Term One](exams/m362k-one-sample-probs.pdf) -- **problems** 

[Practice for In-Term One](exams/m362k-one-sample-solns.pdf) -- **solutions** 

---

**Class 11: February 9th**<br>
Bayes' rule practice.<br>

[Problem packet](problem-sets/sample-p-bayes.pdf)

[Class notes](notes/m362k-feb-09-2024.pdf)

---

**Class 12: February 12th**<br>
Sequences of events <span style="color: purple;">**(Section 1.6)**</span>.<br>

[Class notes](notes/m362k-feb-12-2024.pdf)

---

**Class 13: February 14th**<br>
<span style="color: red;">**In-Term One**</span><br>

[In-Term One](exams/m362k-one-solns.pdf) -- **solutions** 

---

**Class 14: February 16th**<br>
Geometric distribution [cont'd].<br>

[Mathematica demonstration](https://demonstrations.wolfram.com/GeometricDistribution/): The geometric distribution

[Problem Set #2](problem-sets/m362k-ps2-geom-distn-probs.pdf): **Problems**

[Problem Set #2](problem-sets/m362k-ps2-geom-distn-solns.pdf): **Solutions**

The binomial distribution <span style="color: purple;">**(Section 2.1)**</span>.<br>

[Class notes](notes/m362k-feb-16-2024.pdf)

[Homework #3](hw/m362k-hw3-geometric-probs.pdf) -- **due on Friday, February 23rd**

---

**Class 15: February 19th**<br>
More on the binomial distribution <span style="color: purple;">**(Section 2.1)**</span>.<br>

[Wikipedia](https://en.wikipedia.org/wiki/Binomial_theorem): The binomial theorem 

[Wikipedia](https://en.wikipedia.org/wiki/Pascal%27s_triangle): Pascal's triangle

[Mathematica demonstration](https://demonstrations.wolfram.com/BinomialProbabilityDistribution/): The binomial distribution

[Class notes](notes/m362k-feb-19-2024.pdf)

[Homework #4](hw/m362k-hw4-binomial-probs.pdf) -- **due on Friday, March 1st**

---
 
**Class 16: February 21st**<br>
Even more on the binomial distribution <span style="color: purple;">**(Section 2.1)**</span>.<br>

[Problem](problem-sets/p-exam-binom.pdf)

The normal distribution <span style="color: purple;">**(Section 2.2)**</span>.<br>

[Standard Normal Distribution Areas](http://demonstrations.wolfram.com/StandardNormalDistributionAreas/){.demonstrationHyperlink} from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Ian McLeod 

[Class notes](notes/m362k-feb-21-2024.pdf)

---

**Class 17: February 23rd**<br>
More on the normal distribution <span style="color: purple;">**(Section 2.1)**</span>.<br>

[Class notes](notes/m362k-feb-23-2024.pdf)

[Standard normal table](notes/std-normal-table.pdf)

---

**Class 18: February 26th**<br>
More on the normal distribution <span style="color: purple;">**(Section 2.1)**</span>.<br>

[The Normal Distribution](http://demonstrations.wolfram.com/TheNormalDistribution/) from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Ian McLeod 

[Area of a Normal Distribution](http://demonstrations.wolfram.com/AreaOfANormalDistribution/){.demonstrationHyperlink} from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Eric Schulz 

The normal approximation to the binomial distribution <span style="color: purple;">**(Section 2.2)**</span>.<br>

[Class notes](notes/m362k-feb-26-2024.pdf)

---

**Class 19: February 28th**<br>
More on the normal approximation to the binomial distribution <span style="color: purple;">**(Section 2.2)**</span>.<br>

[Mathematica demonstration](http://demonstrations.wolfram.com/IllustratingTheCentralLimitTheoremWithSumsOfBernoulliRandomV/): The Normal Approximation to the Binomial Distribution

[Class notes](notes/m362k-feb-28-2024.pdf)

[Homework #5](hw/m362k-hw5-probs.pdf) -- **due on Friday, March 8th**

[In-Term Two](exams/m362k-two-topics.pdf): Topics

[Practice for In-Term Two](exams/m362k-two-sample-probs.pdf): Problems

[Practice for In-Term Two](exams/m362k-two-sample-solns.pdf): Solutions

---

**Class 20: March 1st**<br>
The Poisson approximation <span style="color: purple;">**(Section 2.4)**</span>.<br>

[Class notes](notes/m362k-mar-01-2024.pdf)

[Wikipedia](https://en.wikipedia.org/wiki/Poisson_distribution): The Poisson distribution

[Mathematica demonstration](https://demonstrations.wolfram.com/PoissonDistribution/#embed): The Poisson Distribution

[Mathematica demonstration](https://demonstrations.wolfram.com/BinomialApproximationToAPoissonRandomVariable/): The Poisson Approximation to the Binomial Distribution

---

**Class 21: March 4th**<br>
Introduction to random variables <span style="color: purple;">**(Section 3.1)**</span>.<br>

[Homework #6](hw/m362k-hw6-normal-approx.pdf) -- **due on Friday, March 22nd**

The cumulative distribution function (cdf) <span style="color: purple;">**(Section 4.5)**</span>.<br>

---

**Class 22: March 6th**<br>
<span style="color: red;">**In-Term Two**</span><br>

---

**Class 23: March 8th**<br>
More on random variables <span style="color: purple;">**(Section 3.1)**</span>.<br>

More on the cumulative distribution function (cdf) <span style="color: purple;">**(Section 4.5)**</span>.<br>

---

**Class 24: March 18th**<br>
Expectation <span style="color: purple;">**(Section 3.2)**</span>.<br>

---

**Class 25: March 20th**<br>
Standard deviation and the normal approximation <span style="color: purple;">**(Section 3.3)**</span>.<br>

<!--
Binomial option pricing: Two periods.<br>

[Problem Set #9](problem-sets/m339d-ps9-two-periods.pdf): **Problems**

[Class notes](notes/m339d-oct-18-2023.pdf) 

---

**Class 26: October 20th**<br>
Multiple binomial periods. <br>

[Class notes](notes/m339d-oct-20-2023.pdf) 

[Problem Set #9](problem-sets/m339d-ps9-two-periods-solns.pdf): **Solutions**

[Homework #9](hw/m339d-hw9-binom.pdf) -- **due on Friday, October 27th**

Monte Carlo for binomial option pricing. <br>

[Problem Set #10](problem-sets/m339d-ps10-binomial-mc-probs.Rmd)

[Problem Set #10](problem-sets/m339d-ps10-binomial-mc-oct-20-2023.Rmd): Phase I

[Homework #8](hw/m339d-hw8-one-period-solns.pdf) -- **solutions**

---

**Class 27: October 23rd**<br>
Monte Carlo for binomial option pricing [cont'd]. <br>

[Problem Set #10](problem-sets/m339d-ps10-binomial-mc-oct-23-2023.Rmd): Phase II

---

**Class 28: October 25th**<br>

[In-Term Two](exams/m339d-two-solns.pdf) -- **solutions** 

---

**Class 29: October 27th**<br>
Review of the normal distribution.<br>

[Standard normal table](notes/std-normal-table.pdf)

[Homework #10](hw/m339d-hw10-normal.pdf) -- **due on Friday, November 3rd**

The normal approximation to the binomial.<br>

[Open Intro Stats Video](https://youtu.be/VvksxAZAlrQ): The normal approximation to the binomial. 

[Problem Set #11](problem-sets/m339d-ps11-dML.pdf): **Problems**

[Class notes](notes/m339d-oct-27-2023.pdf) 

[Problem Set #11](problem-sets/m339d-ps11-dML-solns.pdf): **Solutions**

[Apple parity](data/apple-parity.csv)

[Project #4](projects/m339d-project4-probs.pdf) -- **due on Monday, November 13th**

[Project #4](projects/m339d-project4-probs.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your project 

[Homework #9](hw/m339d-hw9-binom-solns.pdf) -- **solutions**

---

**Class 30: October 30th**<br>
The limiting behavior of stock prices. More on realized returns.<br> 

[Mathematica Code](code/m339d-binomial-tree-limit.nb): Binomial model limit 

[Class notes](notes/m339d-oct-30-2023.pdf) 

---

**Class 31: November 1st**<br>
No class. 

---

**Class 32: November 3rd**<br>
Moment generating functions.<br>

[Class notes](notes/m339d-apr-03-2023.pdf): The pre-limit. mgf.

The log-normal distribution. Jensen's inequality.<br>

[Lecture notes](lectures/m339w-lognormal.pdf): The lognormal distribution

[Class notes](notes/m339d-apr-05-2023.pdf): mgf. The log-normal distribution. Jensen's inequality.

[The Log Normal Distribution](http://demonstrations.wolfram.com/TheLogNormalDistribution/){.demonstrationHyperlink}
from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Chris Boucher 

[Mathematica demonstration](http://demonstrations.wolfram.com/ModelingReturnDistributions/): Modeling return distributions

[Homework #10](hw/m339d-hw10-normal-solns.pdf) - **solutions**


---

**Class 33: November 6th**<br>
Log-normal stock prices: Parameter interpretation.<br>

[Class notes](notes/m339d-nov-06-2023.pdf): Lognormal stock prices: Mean. Median. 

**(Enrichment material)** [Lecture notes](lectures/m339w-on-pricing.pdf): On pricing in the Black-Scholes model with continuous dividends. 

[Problem Set](problem-sets/m339d-ps-lognormal-stocks.pdf): **Problems**

[Problem Set](problem-sets/m339d-ps-lognormal-stocks-solns.pdf): **Solutions**

[Homework #11](hw/m339d-hw11-lognormal-stocks.pdf) -- **due on Friday, November 17th**

---

**Class 34: November 8th**<br>
Log-normal stock prices: Tail probabilities.<br>

[Class notes](notes/m339d-nov-08-2023.pdf): Tail probabilities.

---

**Class 35: November 10th**<br>
Log-normal stock prices: Partial expectation.<br>

[Class notes](notes/m339d-nov-10-2023.pdf): Partial expectation.

---

**Class 36: November 13th**<br>
Log-normal stock prices: Partial expectation [cont'd]. The Black-Scholes pricing formula.<br>

[Wikipedia](http://en.wikipedia.org/wiki/Black%E2%80%93Scholes): Black-Scholes

[The original article by Black and Scholes](http://www.cs.princeton.edu/courses/archive/fall09/cos323/papers/black_scholes73.pdf) 

[Problem Set #12](problem-sets/m339d-ps12-BS.pdf): **Problems**

[Class notes](notes/m339d-nov-13-2023.pdf) 

[Homework #12](hw/m339d-hw12-BS.pdf) -- **due on Friday, December 1st**

---

**Class 37: November 15th**<br>
Black-Scholes [continued].<br> 

[Problem Set #12](problem-sets/m339d-ps12-BS-solns.pdf): **Solutions**

[Problem](problem-sets/mfe-sp2007-p8.pdf)

[Class notes](notes/m339d-nov-15-2023.pdf) 

[Project #5](projects/m339d-project5-probs.pdf) -- **due on Monday, December 4th, 2023**

[Project #5](projects/m339d-project5-probs.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your project 

[In-Term Three](exams/m339d-three-topics.pdf): Topics

[Practice for In-Term Three](exams/m339d-three-sample.pdf) -- **problems** 

[Practice for In-Term Three](exams/m339d-three-sample-solns.pdf) -- **solutions** 

---

**Class 38: November 17th**<br>
Forward-start options. Rolling insurance strategy.<br>

[Problem packet](problem-sets/m339w-bs-forward-start-rolling.pdf)

[Class notes](notes/m339d-nov-17-2023.pdf) 

[Homework #11](hw/m339d-hw11-lognormal-stocks-solns.pdf) -- **solutions**

---

**Class 39: November 27th**<br>
Monte Carlo with Black-Scholes pricing. <br>

[Problem Set #13](problem-sets/m339d-ps13-BS-mc.Rmd): with solutions

[Problem Set #13](problem-sets/m339d-ps13-BS-mc-in-class.Rmd): With in-class code

Focus on the delta.<br>

[Wikipedia](https://en.wikipedia.org/wiki/Greeks_(finance)): Greeks 

[Problem](problem-sets/m339d-ifm-delta.pdf)

[Class notes](notes/m339d-nov-27-2023.pdf) 

---

**Class 40: November 29th**<br>
<span style="color: red;">**In-Term Three**</span><br>

[In-Term Three](exams/m339d-three-solns.pdf) -- **solutions**

---

**Class 41: December 1st**<br>
Delta-hedging. <br>

[Wikipedia](https://en.wikipedia.org/wiki/Market_maker): Market maker.

[Problem](problem-sets/m339d-ifm-delta-hedge.pdf)

[Class notes](notes/m339d-dec-01-2023.pdf) 

[Homework #12](hw/m339d-hw12-BS-solns.pdf) -- **solutions**

---

**Class 42: December 4th**<br>
Delta-hedging [cont'd].

[Class notes](notes/m339d-dec-04-2023.pdf) 

[Extra Homework #13](hw/m339d-hw13-delta.pdf) -- **not to be handed in; final-exam practice**

[Extra Homework #13](hw/m339d-hw13-delta-solns.pdf) -- **solutions**

Options embedded in insurance products: Part I.

[Problem packet](problem-sets/m339d-gmdb-etc.pdf)


---

<!--
[Class notes](notes/m339w-may-02-2022.pdf): GMDB.

[Class notes](notes/m339w-may-04-2022.pdf): Other variable annuities.

[Class notes](notes/m339w-may-06-2022.pdf): Some exotic options.

Options embedded in insurance products: Part II.

Expected return of a portfolio.<br>

[Problem](problem-sets/m339d-ifm-exp-return.pdf)

[Class notes](notes/m339d-sept-12-2022.pdf) 

Volatility of a portfolio. Diversification. Market indices. <br>

[Problems](problem-sets/m339d-vol.pdf)

[Class notes](notes/m339d-sept-14-2022.pdf) 

Feasible sets. Efficient portfolios. Effect of correlation. <br>

[Problems](problem-sets/m339w-vol.pdf)

[Class notes](notes/m339d-sept-16-2022.pdf) 

[Mathematica demonstration](http://demonstrations.wolfram.com/TwoAssetMarkowitzFeasibleSet/): A Two-Asset Markowitz Feasible Set 

[Mathematica demonstration](http://demonstrations.wolfram.com/ThreeAssetEfficientFrontier/): A Three-Asset Feasible Set and Efficient Frontier 

[Problem](problem-sets/m339d-ifm-efficient.pdf)

[September survey](surveys/m339d-sept-survey.docx)

Sharpe ratio.<br>

[Class notes](notes/m339d-sept-19-2022.pdf) 

[Problem](problem-sets/m339d-ifm-sharpe.pdf)

The Capital Asset Pricing Model (CAPM).<br>

[Class notes](notes/m339d-sept-21-2022.pdf) 

[Problem packet](problem-sets/m339d-required-returns.pdf)

[Homework #3](hw/m339d-hw3-intro-corp-finance.pdf) -- **due on Monday, October 3rd**

[Class notes](notes/m339d-sept-26-2022.pdf) 

[Homework #4](hw/m339d-hw4-corp-finance-solns.pdf) -- **solutions**

---
***
---

Implied volatility. <br>

[Problem](problem-sets/m339d-ifm-impl-vol.pdf)

---

[The Final Exam](exams/m339d-final-topics.pdf): Topics

[Quiz #2](quizzes/m339d-quiz-two.pdf) -- due on **Monday, January 24th**

[Quiz #3](quizzes/m339d-quiz-three.pdf) -- **due on Wednesday, January 26th**

[Quiz #4](quizzes/m339d-quiz4.pdf) -- **due on Monday, January 31st**

[Quiz #5](quizzes/m339d-quiz5-cont-div.pdf) -- **due on Wednesday, February 2nd**

[Quiz #7](quizzes/m339d-quiz7-leveraging.pdf) -- **due on Wednesday, February 9th**

[Quiz #8](quizzes/m339d-quiz8-two-assets.pdf) -- **due on Monday, February 14th**

[Problem Set #5](problem-sets/m339d-ps-five-yuri-one.pdf): **Problems**

[Problem Set #5](problem-sets/m339d-ps-five-yuri-one-solns.pdf): **Solutions**

[Problem Set #6](problem-sets/m339d-ps-six-yuri-two.pdf): **Problems**

[Problem Set #6](problem-sets/m339d-ps-six-yuri-two-solns.pdf): **Solutions**

[Problem Set #7](problem-sets/m339d-ps-seven-forwards-hedging.pdf): **Problems**

[Problem Set #7](problem-sets/m339d-ps-seven-forwards-hedging-solns.pdf): **Solutions**

[Quiz #9](quizzes/m339d-quiz9-forwards.pdf) -- **due on Wednesday, February 16th**

[Class notes](notes/m339d-feb-14-2022.pdf): Covered/naked option writing. European put options.

[Quiz #10](quizzes/m339d-quiz10-calls.pdf) -- **due on Monday, February 28th**

[Problem Set #8](problem-sets/m339d-ps-eight-forwards-calls-puts-probs.pdf): **Problems**

[Problem Set #8](problem-sets/m339d-ps-eight-forwards-calls-puts-solns.pdf): **Solutions**

**Suggested problems:** Sample SoA problems (IFM exam: Derivatives: Intro): \#12, \#26, \#35, \#48, \#49, \#61, \#62, \#66, \#75 (European put options, moneyness)

Collars. Derivative securities.<br>

[Class notes](notes/m339d-feb-18-2022.pdf): Collars. Derivative securities. 

**Suggested problems:** Sample SoA problems (IFM exam: Derivatives: Introductory): #24 (rationale for the existence of derivatives)

[Quiz #11](quizzes/m339d-quiz11.pdf) -- **due on Wednesday, March 2nd**

Dynamic portfolios. 

[Class notes](notes/m339d-feb-21-2022.pdf): Arbitrage portfolios. Law of the Unique Price. Replicating portfolios.

Pricing prepaid forwards and forwards on stocks.<br>

[Problem packet](problem-sets/m339d-forwards-futures.pdf)

[Class notes](notes/m339d-feb-25-2022.pdf): Pricing prepaid forwards and forwards on stocks.

**Suggested problems**: Sample SoA problems (IFM: Derivatives: Introductory): #20, #21, #29

[Quiz #12](quizzes/m339d-quiz12-parity-prep.pdf) -- **due on Monday, March 7th**

---

More on synthetic forwards. Futures.<br>

[Class notes](notes/m339d-feb-28-2022.pdf): Synthetic forwards. Futures.

**Suggested problems:** Sample SoA problems (IFM exam: Derivatives: Introductory): #30, #32, #45, #69 (futures)

---

[Quiz #13](quizzes/m339d-quiz13-parity.pdf) -- **due on Wednesday, March 9th**

---

[Class notes](notes/m339d-mar-04-2022.pdf): Synthetic forwards (revisited). Chooser options. 

---

Gap options.<br>

[Lecture Twelve](lectures/m339d-lecture-twelve-gap-options-empty.pdf): Gap options (skeleton).

[Class notes](notes/m339d-mar-07-2022.pdf): Equity-linked contracts. Gap options.

[Quiz #14](quizzes/m339d-quiz14-gaps.pdf) - **due on Monday, March 21st**

---

Options on currencies.<br>

[Class notes](notes/m339d-mar-09-2022.pdf): Currency options.

---

Exchange options.<br>

[Problem](problem-sets/m339d-mfe-2007-p6.pdf)

[Class notes](notes/m339d-mar-11-2022.pdf): Exchange options. Generalized put-call parity.

[Quiz #15](quizzes/m339d-quiz15-exchange.pdf) - **due on Wednesday, March 23rd**

[Quiz #16](quizzes/m339d-quiz16-exchange-exp.pdf) - **due on Monday, March 28th**

Bounds on option prices.<br>

[Class notes](notes/m339d-mar-21-2022.pdf): Bounds on call prices.

---

Bounds on put prices. Monotonicity of call prices. Bull spreads. <br>

[Class notes](notes/m339d-mar-23-2022.pdf): Bounds on put prices. Monotonicity of call prices. Bull spreads.

---

Monotonicity of put prices. "Cord-slope" bounds. Bear spreads.<br>

[Problem](problem-sets/m339d-properties.pdf)

[Class notes](notes/m339d-mar-25-2022.pdf): Monotonicity of put prices. "Cord-slope" bounds. Bear spreads. 

---

Convex functions. Convexity of put/call prices. Butterfly spreads.<br>

[Class notes](notes/m339d-mar-30-2022.pdf): Convexity of call prices. Butterfly spreads.

---

Put-price convexity. Butterfly-spread practice.<br> 

[Problem packet](problem-sets/m339d-butterflies.pdf)

[Class notes](notes/m339d-apr-01-2022.pdf): Put-price convexity. More on butterfly spreads. 

---

Straddles. Strangles.<br>

[Class notes](notes/m339d-apr-04-2022.pdf): Speculating on volatility. Collars revisited. 

**Suggested problems**: Sample SoA problems (IFM exam: Derivatives: Introductory): #8, #16 Sample SoA problems (IFM exam: Derivatives: Advanced): #40 (spreads, strangles, straddles)

[Quiz #17](quizzes/m339d-quiz17-properties.pdf) - **due on Wednesday, April 6th**

[Homework #7](hw/m339d-hw7-price-properties.pdf) - **due on Friday, April 8th**

[Quiz #18](quizzes/m339d-quiz-thirteen-straddles.pdf) - **due on Monday, April 11th**

---

More on collars. Ratio spreads. Box spreads.<br>

[Problem packet](problem-sets/m339d-collar-ratio-box.pdf)

[Class notes](notes/m339d-apr-06-2022.pdf): More on collars. Ratio spreads. Box spreads. 

[Quiz #19](quizzes/m339d-quiz19-box-ratio.pdf) - **due on Wednesday, April 13th**

---

[Problem Set #9](problem-sets/m339d-ps-nine-bin-pricing.pdf): **Problems**

[Quiz #20](quizzes/m339d-quiz20-delta-B.pdf) - **due on Monday, April 18th**

[Quiz #21](quizzes/m339d-quiz21-binomial.pdf) - **due on Wednesday, April 20th**

---

Binomial option pricing: Graphical interpretation.<br>

[Class notes](notes/m339d-apr-13-2022.pdf): Binomial option pricing practice. Graphical interpretation of a call's replicating portfolio.

---

Binomial option pricing: The forward tree.<br>

[Class notes](notes/m339d-apr-15-2022.pdf): The forward tree. 

[Problem Set #10](problem-sets/m339d-ps-ten-two-periods.pdf) -- **problems**

[Class notes](notes/m339d-apr-18-2022.pdf): Two periods.

---

Multiple binomial periods. Early exercise (revisited).<br>

[Problem packet](problem-sets/m339d-early-exercise.pdf)

[Class notes](notes/m339d-apr-20-2022.pdf): Binomial option pricing (more periods). Early exercise.

[Quiz #22](quizzes/m339d-quiz22-Amer-binom-prep.pdf) - **due on Monday, April 25th**

---

Binomial pricing of American options. <br>

[Problem packet](problem-sets/m339d-american.pdf)

[Class notes](notes/m339d-apr-22-2022.pdf): Binomial pricing of American options.

**Suggested problems:** Sample IFM (Derivatives: Advanced) Problem \#44 (binomial pricing of American options)


---

Binomial pricing of American option [practice].<br>

[Class notes](notes/m339d-apr-25-2022.pdf): Binomial pricing of American options (practice).

---

Properties of American-option prices. Asian options.<br>

[Class notes](notes/m339d-apr-27-2022.pdf): Bounds on American option prices. Definition of Asian options. 

**Suggested problems:** Sample IFM (Derivatives: Advanced) Problem \#26 (bounds on European and American option prices)

[Quiz #23](quizzes/m339d-quiz23-American.pdf) - **due on Thursday, April 28th**

[Quiz #24](quizzes/m339d-quiz24-Asian.pdf) - **due on Monday, May 2nd**

---

Asian-option pricing. Barrier options.<br>

[Class notes](notes/m339d-apr-29-2022.pdf): More on Asian options. Barrier options. 

[Slides](notes/m339d-barrier.pdf): Barrier options.

---

Barrier options.<br>

[Problem packet](problem-sets/m339d-barrier.pdf)

[Class notes](notes/m339d-may-02-2022.pdf): More on barrier options. 

[Quiz #25](quizzes/m339d-quiz25-barrier.pdf) - **due on Wednesday, May 4th**

---

**Class 43: May 4th**<br>
Compound options.<br>

[Slides](notes/m339d-compound.pdf): Compound options.

[Homework #11](hw/m339d-hw11-exotic.pdf) - **not to be handed in**

Binomial pricing of options on currencies.<br>

[Problem](problem-sets/m339d-bin-currency.pdf)

[Class notes](notes/m339d-may-04-2022.pdf): Compound options. Currency options (the binomial model).

Binomial pricing of options on futures contracts.<br>

[Problem](problem-sets/m339d-bin-futures.pdf)

[Class notes](notes/m339d-may-06-2022.pdf): Futures options (the binomial model). 

[Problem Set #11](problem-sets/m339d-ps11-currency-futures.pdf) -- **problems**

[Problem Set #11](problem-sets/m339d-ps11-currency-futures-solns.pdf) -- **solutions**
-->
