---
title: "Homework assignment #6"
author: "Milica Cudina"
date: "`r Sys.Date()`"
output: pdf_document
---
<!-- The author of this template is Dr. Gordan Zitkovic.-->
<!-- The code chunk below contains some settings that will  -->
<!-- make your R code look better in the output pdf file.  -->
<!-- If you are curious about what each option below does, -->
<!-- go to https://yihui.org/knitr/options/ -->
<!-- If not, feel free to disregard everything ...  -->
```{r echo=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.align="center",
  fig.pos="t",
  strip.white = TRUE,
  tidy = TRUE
)
```
<!-- ... down to here. -->

# Textbook exercises
## Problem 1. ($1+1+1+2=5$ points)
Solve **Problem 4.2** from the textbook. 

*Solution:*

## Problem 2. ($1+3+2+2+2+3=13$ points)
Solve **Problem 4.4** from the textbook. 

*Solution:*

## Problem 3. ($3+3=6$ points)
Solve **Problem 4.6** from the textbook. 

*Solution:*

## Problem 4. ($3+3=6$ points)
Solve **Problem 4.8** from the textbook. 

*Solution:*

## Problem 5. ($5$ points)
Solve **Problem 4.10** from the textbook. 

*Solution:*

\newpage

# Additional problems
## Problem 6. ($3\times 2 = 6$ points)
Let $Z$ be a standard normal random variable. Using the standard normal tables, calculate the following probabilities: 
\begin{itemize}
  \item[(i)] $\mathbb{P}[ -1.23 < Z < 2.37]$  
  \item[(ii)] $\mathbb{P}[ 1/Z < 1]$
  \item[(iii)] $\mathbb{P}[ Z^2 > 2.56]$
\end{itemize}

*Solution:*

## Problem 7. ($4+5=9$ points)
*Source: Problem \#139 from Moore-McCabe-Craig.*

The interquartile range (IQR) of a distribution is defined as the
distance between the first and the third quartiles. 
\begin{itemize}
\item[(i)] ($4$ points) What is the IQR for the standard normal
  distribution? 
\item[(ii)] ($5$ points) What is the IQR for a normal distribution
  with mean $\mu$ and variance $\sigma^2$?
\end{itemize}

*Solution:*
