---
title: "Predictive Analytics (M339G=M389G)"
output: html_document
---

<style>
  hr {
      position: relative; 
            top: 20px; 
            border: none; 
            height: 2px; 
            background: black; 
            margin-bottom: 50px; 
  }
</style>

---

**Important external links**

[Cornell Notes](http://lsc.cornell.edu/how-to-study/taking-notes/cornell-note-taking-system/)

[Guide to the SoA written exams](https://www.soa.org/globalassets/assets/files/edu/edu-guide-to-written-exam.pdf) 

---

**The textbook, lecture notes, and the like**

[Materials on R](https://gordanz.github.io/stochastic-book/intro.html)

[Introduction to Statistical Learning](https://www.statlearning.com)

[Computer Age Statistical Inference: Algorithms, Evidence and Data Science](https://hastie.su.domains/CASI/)

[Elements of Statistical Learning](https://hastie.su.domains/ElemStatLearn/)

[Mathematical Statistics with Applications in `R`](https://search.lib.utexas.edu/permalink/01UTAU_INST/be14ds/alma991058130777506011)

---

**A few "shortcuts" for R and RStudio**

Here are some resources I created for *Applied Statistics*. They will be useful in this course as well and can be used in conjunction with our lecture notes. 

[R (main website)](https://www.r-project.org/)

[RStudio (main website)](https://rstudio.com/)

[The instructions slideshow](instructions/m358k-R-instructions.html)

[The basic R slideshow](instructions/m358k-basic-R.html)

[The basic R "cheatsheet"](https://raw.githubusercontent.com/rstudio/cheatsheets/master/base-r.pdf)

[If ... else](https://www.datamentor.io/r-programming/if-else-statement/)

[A tutorial on functions in R](https://www.tutorialspoint.com/r/r_functions.htm)

[Working directory in `R`](https://r-coder.com/working-directory-r/)

[Rmd cheatsheet](instructions/rmarkdown-cheatsheet.pdf)

[Homework Instructions](instructions/m358k-hw-instructions.html) -- if in doubt, read and understand all of this before you work on your homework/project

[Homework Template](instructions/homework-template.Rmd) -- this is an optional template you can use to complete your homework assignments and projects 

---

**Class 1: August 25th, 2025**<br>
Orientation. `R` Markdown.<br>

[A role model](pics/bilbo.jpeg)

[First-Day Handout](syllabus/syllabus-58860.html)

[Homework #1](hw/m339g-hw1-prereqs.pdf) -- **due on Friday, September 5th, 2025**

---

**Class 2: August 27th, 2025**<br>
Some Review from Mathematical Statistics.<br> 

[Class notes](notes/m339g-aug-27-2025.pdf)

---

**Class 3: August 29th, 2025**<br>
Resampling Methods (Sampling Distribution and Univariate Bootstrap) <span style="color: purple;">**(Sections 5.2 and 5.3.4)**</span>.<br>

[Class notes](notes/m339g-aug-29-2025.pdf)

[Wikipedia](https://en.wikipedia.org/wiki/Shapiro–Wilk_test): The Shapiro-Wilk test

[Data set](code/temperatures.csv): Human temperatures

[`R`-notebook](code/temperature.Rmd): Temperature bootstrap

[Data set](code/bangladesh-data.csv): Chemicals in Bangladesh

[`R`-notebook from class](code/arsenic-in-class.Rmd): Arsenic (complete)

---

**Class 4: September 3rd, 2025**<br>
Resampling Methods (Bootstrap, cont’d) <span style="color: purple;">**(Sections 5.2 and 5.3.4)**</span>.<br>

[Class notes](notes/m339g-sept-03-2025.pdf)

[Slides by Hastie & Tibshirani](slides/ch5-univariate-bootstrap.pdf): Univariate bootstrap

[`R`-notebook from class](code/two-stock-portfolio.Rmd): Two-stock portfolio

---

**Class 5: September 5th, 2025**<br>
Prediction and inference <span style="color: purple;">**(Section 2.1.1)**</span>.<br>

[WMT data](data/WMT.csv)

[IBM data](data/IBM.csv)

[NASDAQ data](data/ndq.csv)

[Project #1](projects/m339g-project1-probs.pdf) -- **due on Monday, September 22nd, 2025**

[Project #1](projects/m339g-project1-probs.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your project 

[Homework #1](hw/m339g-hw1-prereqs-solns.pdf) -- **solutions**

---

**Class 6: September 8th, 2025**<br>
More on prediction and inference <span style="color: purple;">**(Section 2.1.1)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch2-prediction.pdf): Prediction 

[Class notes](notes/m339g-sept-08-2025.pdf)

[Nobody Expects $L^1$](https://mathoverflow.net/questions/178139/examples-of-unexpected-mathematical-images?newreg=78ec2c4c5b154caeaca68ac602031827)

---

**Class 7: September 10th, 2025**<br>
Simple Linear Regression. <span style="color: purple;">**(Section 3.1)**</span>.<br>

[Class notes](notes/m339g-sept-10-2025.pdf)

[Slides by Hastie & Tibshirani](slides/ch3-simple-linear-regression.pdf): Simple linear regression

[Homework #2](hw/m339g-hw2-regression.pdf) -- **due on Friday, September 19th, 2025**

---

**Class 8: September 12th, 2025**<br>
More on linear regression.<br>

[`R`-script for class](code/slr-conf-ints.R): Simple linear regression

More on Resampling Methods (Sampling Distribution of the Slope Coefficient) <span style="color: purple;">**(Section 5.3.4)**</span>.<br>

[`R`-notebook from class](code/slr-coeffs.Rmd): Bootstrap for simple linear regression

[`R`-script from class](code/insulation-lm.R): Polynomial fit

[Homework #3](hw/m339g-hw3-slr.pdf) -- **due on Friday, September 26th, 2025**

---

**Class 9: September 15h, 2025**<br>
Simple Linear Regression: Cross Validation <span style="color: purple;">**(Section 5.1.1, 5.1.2, 5.1.3, 5.3.1, 5.3.2, 5.3.3)**</span>.<br>

[Class notes](notes/m339g-sept-15-2025.pdf)

[Slides by Hastie & Tibshirani](slides/ch5-crossvalidation.pdf): Cross-validation 

[`R`-notebook from class](code/cars-validation.Rmd): Cross-validation for simple linear regression

---

**Class 10: September 17th, 2025**<br>
Multiple linear regression <span style="color: purple;">**(Section 3.2.1)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch3-multiple-linear-regression-intro.pdf): Multiple linear regression 

[Wikipedia](https://en.wikipedia.org/wiki/Projection_matrix): Projection matrix

[Wikipedia](https://en.wikipedia.org/wiki/Leverage_(statistics)): Leverage

[Class notes](notes/m339g-mlr.pdf)

[`R`-notebook from class](code/mlr.Rmd): Multiple linear regression

---

**Class 11: September 19th, 2025**<br>
Multiple linear regression (cont'd) <span style="color: purple;">**(Section 3.2.1)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch3-mlr-hierarchy.pdf): Multiple linear regression (cont'd) 

[Code from class](code/trees-in-class.Rmd): Cherry trees

[Class notes](notes/m339g-sept-19-2025.pdf): $F-$distribution. 

[My old class notes from *Math Stats*](notes/m378k-mar-07-2025.pdf): Sample variance. 

[`R`-script from class](code/F-distn.R): The $F-$distribution

[Homework #2](hw/m339g-hw2-regression-solns.pdf) -- **solutions**

---

**Class 12: September 22nd, 2025**<br>
Multiple linear regression (cont'd) <span style="color: purple;">**(Section 3.2.1)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch3-mlr-contd.pdf): Multiple linear regression (cont'd) 

[Wikipedia](https://en.wikipedia.org/wiki/Curse_of_dimensionality): Curse of dimensionality

[Wikipedia](https://en.wikipedia.org/wiki/Mallows%27s_Cp): Mallows' $C_p$

[Wikipedia](https://en.wikipedia.org/wiki/Akaike_information_criterion): Akaike information criterion

[Wikipedia](https://en.wikipedia.org/wiki/Bayesian_information_criterion): Bayesian information criterion

[Wikipedia](https://en.wikipedia.org/wiki/Coefficient_of_determination#Adjusted_R2): Adjusted $R^2$

[Data for class](code/mustangs.csv): Mustangs

[Code from class](code/mustangs.Rmd): Mustangs

[Homework #4](hw/m339g-hw4-F.pdf) -- **due on Friday, October 3rd, 2025**

Splines <span style="color: purple;">**(Section 7.4)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch7-linear-splines.pdf): Intro to Splines 

[Class notes](notes/m339g-sept-22-2025.pdf)

---

**Class 13: September 24th, 2025**<br>
More on splines <span style="color: purple;">**(Section 7.4)**</span>.<br>

[Data for class](code/salesadv.csv): Sales

[Code for class](code/ads.Rmd): Ads

[Slides by Hastie & Tibshirani](slides/ch7-cubic-splines.pdf): Cubic Splines

[Class notes](notes/m339g-sept-24-2025.pdf)

---

**Class 14: September 26th, 2025**<br>
More on splines <span style="color: purple;">**(Section 7.4)**</span>.<br>

[`R`-notebook from class](code/splines.Rmd): Splines 

[Code for class](code/splines-validation.Rmd): Splines with validation

The Trade-Off Between Prediction Accuracy and Model Interpretability <span style="color: purple;">**(Section 2.1.3)**</span>.<br>

[Wikipedia](https://en.wikipedia.org/wiki/Thin_plate_spline): Thin-plate spline

[Slides by Hastie & Tibshirani](slides/ch2-interpretability.pdf): Bias-variance trade-off and interpretability

[Homework #3](hw/m339g-hw3-slr-solns.pdf) -- **solutions**

---

**Class 15: September 29th, 2025**<br>
Categorical predictiors.<br>

[Slides by Hastie & Tibshirani](slides/ch3-dummies.pdf): Qualitative/categorical predictors

[`R`-notebook for class](code/carseats-dummies.Rmd): Qualitative/categorical predictors

Introduction to Classification.<br>

[Class notes](notes/m339g-sept-29-2025.pdf)

---
 
**Class 16: October 1st, 2025**<br>
Regression vs Classification Problems <span style="color: purple;">**(Section 2.1.5)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch2-classification.pdf): Approaches to classification

Logistic regression <span style="color: purple;">**(Sections 4.2, 4.3)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch4-classification.pdf): Logistic regression

---

**Class 17: October 3rd, 2025**<br>
Logistic-regression labs.<br>

[Wikipedia](https://en.wikipedia.org/wiki/Stock_market_index): Stock market index

[`R`-notebook for class](code/stocks-logistic-reg.Rmd): Logistic regression with the stock market

[`R`-notebook for class](code/med-school.Rmd): Logistic regression with medical school

[Class notes](notes/m339g-oct-03-2025.pdf)

[Homework #4](hw/m339g-hw4-F-solns.pdf) -- **solutions**

---

**Class 18: October 6th, 2025**<br>
Logistic regression with multiple response categories.<br>

[Slides by Hastie & Tibshirani](slides/ch4-multi-logistic.pdf): Logistic regression with multiple response categories

[Class notes](notes/m339g-oct-06-2025.pdf)

[Data for class](code/hsbdemo.csv): School choice

[`R`-notebook for class](code/vocation.Rmd): Multiclass logistic regression 

[Homework #5](hw/m339g-hw5-logistic.pdf) -- **due on Friday, October 10th, 2025**

[Homework #6](hw/m339g-hw6-sample-one.pdf) -- **for practice; not to be handed in**

[Homework #6](hw/m339g-hw6-sample-one-solns.pdf) -- **solutions**

Mock exam.<br>

[Mock Exam](exams/m339g-mock-exam-probs.pdf) -- **problems** 

[Mock Exam](exams/m339g-mock-exam-solns.pdf) -- **solutions** 

---

**Class 19: October 8th, 2025**<br>
K-Nearest Neighbors <span style="color: purple;">**(Section 2.2.3, 4.7.6)**</span>.<br>

[`R`-notebook for class](code/knn-caravans.Rmd): KNN for insurance policies

Collinearity <span style="color: purple;">**(Section 3.3.3)**</span>.<br>

[`R`-notebook for class](code/collinearity.Rmd): Simulated collinearity

[Class notes](notes/m339g-vif.pdf): VIF

[`R`-notebook for class](code/vif.Rmd): Variance inflation factor

[In-Term One](exams/m339g-one-topics.pdf): Topics

[Practice for In-Term One](exams/m339g-one-sample-probs.pdf) -- **problems** 

[Practice for In-Term One](exams/m339g-one-sample-solns.pdf) -- **solutions** 

---

**Class 20: October 10th, 2025**<br>
Supervised vs Unsupervised Learning  <span style="color: purple;">**(Section 2.1.4)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch1-supervised-unsupervised.pdf): Supervised vs. unsupervised learning

K-Means Clustering <span style="color: purple;">**(Section 12.4.1)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch12-clustering.pdf): K-Means Clustering 

[Towards Data Science](https://towardsdatascience.com/three-versions-of-k-means-cf939b65f4ea): K-Means Clustering

[Medium](https://medium.com/analytics-vidhya/comparison-of-initialization-strategies-for-k-means-d5ddd8b0350e): More on Initialization for K-Means Clustering

[UC Irvine MLR](https://archive.ics.uci.edu/dataset/267/banknote+authentication): Data documentation with expanded data set

[Data for class](code/banknotes.csv): Banknotes

[Code for class](code/banknotes-k-means.Rmd): K-Means Clustering

[Homework #5](hw/m339g-hw5-logistic-solns.pdf) -- **solutions**

[Homework #7](hw/m339g-hw7-k-means.pdf) -- **due on Friday, October 24th, 2025**

---

**Class 21: October 13th, 2025**<br>
Singular value decomposition <span style="color: purple;">**(Section 12.2)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch12-intro.pdf): Introduction to PCA

[Class notes](notes/m339g-oct-13-2025.pdf)

[Extra class notes](notes/m339g-feb-23-2024.pdf)

[YouTube](https://youtu.be/rYz83XPxiZo?si=nkvOk6GNor638x29): A beautiful lecture by Prof. Gilbert Strang

[Extra-Credit Homework](hw/m339g-ec-hw-svd.pdf) -- **due on Friday, October 31st, 2025**

---

**Class 22: October 15th, 2025**<br>
<span style="color: red;">**In-Term One**</span><br>

[In-Term One](exams/m339g-one-solns.pdf) -- **solutions** 

---

**Class 23: October 17th, 2025**<br>
Principal component analysis (PCA) <span style="color: purple;">**(Section 12.2)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch12-pca.pdf): PCA

PCA lab.<br>

[`R`-notebook for class](code/pca.Rmd): Principal component analysis

[Data for class](code/housepriceall.csv): Houses

[`R`-notebook for class](code/pca-houses.Rmd): Principal component analysis for houses

---

**Class 24: October 20th, 2025**<br>
Principal components regression <span style="color: purple;">**(Section 6.3.1)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch6-pcr.pdf): PCR

<!--
More about the principal components regression <span style="color: purple;">**(Section 6.3.1)**</span>.<br>
-->

[`R`-notebook for class](code/pcr.Rmd): Principal component regression

[`R`-notebook for class](code/pcr-seat-position.Rmd): Principal component regression on seat positions

Principal components analysis and clustering <span style="color: purple;">**(Section 12.2 and 12.4.1)**</span>.<br>

[UC Irvine MLR](https://archive.ics.uci.edu/dataset/236/seeds): Documentation for the `seeds` data set 

[Data set](code/seeds_dataset.csv)

[`R`-notebook for class](code/pca-kmeans.Rmd): Principal component analysis with K-means

[Project #2](projects/m339g-project2-probs.pdf) -- **due on Monday, November 10th, 2025**

[Project #2](projects/m339g-project2-probs.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your project 

---

**Class 25: October 22nd, 2025**<br>
Linear discriminant analysis <span style="color: purple;">**(Section 4.4.1)**</span>.<br>

[Class notes](notes/m339g-oct-22-2025.pdf)

[Slides by Hastie & Tibshirani](slides/ch4-lda-intro.pdf): Linear discriminant analysis for $p=1$

---

**Class 26: October 24th, 2025**<br>
More on LDA <span style="color: purple;">**(Section 4.4.1)**</span>. Bivariate normal distribution.<br> 

[Class notes](notes/m339g-oct-24-2025.pdf)

[Homework #7](hw/m339g-hw7-k-means-solns.pdf) -- **solutions**

---

**Class 27: October 27th, 2025**<br>
More on the bivariate normal distribution.<br> 

<!--
[Class notes](notes/m339g-mar-12-2025.pdf)
-->

[Mathematica demonstration](https://demonstrations.wolfram.com/TheBivariateNormalDistribution/): The Bivariate Normal Distribution

[Mathematica demonstration](https://demonstrations.wolfram.com/TheBivariateNormalAndConditionalDistributions/): The Bivariate Normal and Conditional Distributions

<!--
[Class notes](notes/m339g-mar-14-2025.pdf)


Multivariate normal distribution.<br> 

[Class notes](notes/m339g-mar-24-2025.pdf)

---

**Class 28: March 26th, 2025**<br>
More on the linear discriminant analysis, quadratic discriminant analysis, naive Bayes <span style="color: purple;">**(Section 4.4.1)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch4-lda.pdf): More on linear discriminant analysis 

[Wikipedia](https://en.wikipedia.org/wiki/Receiver_operating_characteristic): The Receiver Operating Characteristic (ROC)

---

**Class 29: March 28th, 2025**<br>
More on the linear discriminant analysis, quadratic discriminant analysis, naive Bayes <span style="color: purple;">**(Section 4.4.1)**</span>.<br>

[`R`-notebook for class](code/lda.Rmd): LDA, QDA, and Naive Bayes

[`partimat`](https://www.rdocumentation.org/packages/klaR/versions/1.7-3/topics/partimat): Documentation

[`R`-notebook for class](code/lda-banknotes.Rmd): Partition plots

[Homework #8](hw/m339g-hw8-lda-qda.pdf) -- **due on Friday, April 4th, 2025**

[Project #3](projects/m339g-project3-probs.pdf) -- **due on Monday, April 28th, 2025**

[Project #3](projects/m339g-project3-probs.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your project 

---

**Class 30: March 31st, 2025**<br>
Tree-based regression <span style="color: purple;">**(Section 8.1.1)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch8-tree-based-regression.pdf): Tree-based regression

[Homework #9](hw/m339g-hw9-reg-trees.pdf) -- **due on Friday, April 11th, 2025**

---

**Class 31: April 2nd, 2025**<br>
More on tree-based regression <span style="color: purple;">**(Section 8.1.1)**</span>.<br>

[Problem packet](problem-sets/m339g-regression-trees.pdf)

[Class notes](notes/m339g-mar-31-2025.pdf): Regression trees.

Tree-based regression: pruning <span style="color: purple;">**(Section 8.1.1)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch8-pruning.pdf): Tree-based regression (pruning)

[Problem packet](problem-sets/m339g-pruning-classification.pdf)

[Class notes](notes/m339g-apr-02-2025.pdf): Pruning.

[`tree` documentation](https://cran.r-project.org/web/packages/tree/tree.pdf)

[`R`-notebook for class](code/regression-trees.Rmd): Regression trees


---

**Class 32: April 4th, 2025**<br>
Classification trees <span style="color: purple;">**(Section 8.1.2)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch8-classification-trees.pdf): Tree-based classification

[Class notes](notes/m339g-apr-04-2025.pdf): Classification trees.

[Homework #8](hw/m339g-hw8-lda-qda-solns.pdf) -- **solutions**

[Homework #10](hw/m339g-hw10-class-trees.pdf) -- **due on Friday, April 18th, 2025**

---

**Class 33: April 7th, 2025**<br>
Even more on decision trees <span style="color: purple;">**(Sections 8.1.3 and 8.1.4)**</span>.<br>

[Class notes](notes/m339g-apr-07-2025.pdf): Classification trees.

[`R`-notebook for class](code/classification-trees.Rmd): Classification trees

[Slides by Hastie & Tibshirani](slides/ch8-single-tree-epilogue.pdf): Tree-based methods pros and cons

---

**Class 34: April 9th, 2025**<br>
Bagging <span style="color: purple;">**(Section 8.2.1)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch8-bagging.pdf): Bagging

[`R`-script from class](code/0-632.R): 0.632 

Random forests <span style="color: purple;">**(Section 8.2.2)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch8-random-forests.pdf): Random forests

[Problem](problem-sets/srm-sample-p39.pdf)

[Class notes](notes/m339g-apr-09-2025.pdf): 0.632. Random forests.

---

**Class 35: April 11th, 2025**<br>
Mock exam.<br>

[Mock Exam](exams/m339g-mock-two-solns.pdf) -- **solutions** 

[Homework #9](hw/m339g-hw9-reg-trees-solns.pdf) -- **solutions**

---

**Class 36: April 14th, 2025**<br>
Boosting <span style="color: purple;">**(Section 8.2.3)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch8-boosting.pdf): Boosting

[Homework #11](hw/m339g-hw11-more-trees.pdf) -- **due on Friday, April 25th, 2025**

More on bagging, random forests, and boosting <span style="color: purple;">**(Section 8.3.3)**</span>.<br>

[`R`-notebook for class](code/bagging-random-forests.Rmd): Bagging, random forests, boosting. 

Lines, planes, hyperplanes.<br>

[Class notes](notes/m339g-apr-14-2025.pdf): Lines.

[In-Term Two](exams/m339g-two-topics.pdf): Topics

[Practice for In-Term Two](exams/m339g-two-sample-probs.pdf) -- **problems** 

[Practice for In-Term Two](exams/m339g-two-sample-solns.pdf) -- **solutions** 


---

**Class 37: April 16th, 2025**<br>
<span style="color: red;">**In-Term Two**</span><br>

[In-Term Two](exams/m339g-two-solns.pdf) -- **solutions** 

---

**Class 38: April 18th, 2025**<br>
Maximal margin classifier <span style="color: purple;">**(Section 9.1)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch9-maximal-margin-classifier.pdf): Maximal margin classifier

[Class notes](notes/m339g-apr-18-2025.pdf): Hyperplanes. Lagrange multipliers.

[Homework #10](hw/m339g-hw10-class-trees-solns.pdf) -- **solutions**

---

**Class 39: April 21st, 2025**<br>
More on the maximal margin classifier <span style="color: purple;">**(Section 9.1)**</span>.<br>

[Class notes](notes/m339g-apr-21-2025.pdf): Maximal margin classifier.

---

**Class 40: April 23rd, 2025**<br>
Support vector classifier <span style="color: purple;">**(Section 9.2)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch9-support-vector-classifier.pdf): Support vector classifier

[Class notes](notes/m339g-nov-22-2024.pdf): Support vector classifier. 

More on the support vector classifier <span style="color: purple;">**(Section 9.2)**</span>.<br>

[`R`-notebook for class](code/support-vector-classifier.Rmd): Support vector classifier. 

---

**Class 41: April 25th, 2025**<br>
Support vector machines <span style="color: purple;">**(Section 9.3)**</span>.<br>

[Slides by Hastie & Tibshirani](slides/ch9-nonlinearity.pdf): Inspiration for support vector machines

[Slides by Hastie & Tibshirani](slides/ch9-svm.pdf): Support vector machines

[Homework #11](hw/m339g-hw11-more-trees-solns.pdf) -- **solutions**

---

[The Final Project](projects/m339g-final-project-probs.pdf) -- **due on Thursday, May 1st, 2025**

[The Final Project](projects/m339g-final-project-probs.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your project 

---

**Class 42: April 28th, 2025**<br>
A Quick Review of Hypothesis Testing <span style="color: purple;">**(Section 13.1)**</span>.<br>

[Slides by James & Witten](slides/ch13-quick-hypothesis.pdf): Review of Hypothesis Testing

[`R`-script from class](code/single-hypothesis.R)


The Challenge of Multiple Testing <span style="color: purple;">**(Section 13.2)**</span>.<br>

[Slides by James & Witten](slides/ch13-multiple-testing.pdf): Multiple Testing

The False Discovery Rate <span style="color: purple;">**(Section 13.4)**</span>.<br>

[Slides by James & Witten](slides/ch13-false-discovery-rate.pdf): False Discovery Rate

---

A [blog post](https://fivethirtyeight.com/features/science-isnt-broken/#part1) on **p-hacking** with an interactive component (pardon the expletives!)

---

<!--
Odds and Ends.<br>

Review of categorical predictors and logistic regression.<br>

[Class notes](notes/m339g-mar-01-2024.pdf)


-->
