---
title: "Introduction to Financial Mathematics for Actuaries (M339D=M389D)"
output: 
  html_document
---

<style>
  hr {
      position: relative; 
            top: 20px; 
            border: none; 
            height: 2px; 
            background: black; 
            margin-bottom: 50px; 
  }
</style>

---

**Important external links**

[Cornell Notes](http://lsc.cornell.edu/how-to-study/taking-notes/cornell-note-taking-system/)

[Guide to the SoA written exams](https://www.soa.org/globalassets/assets/files/edu/edu-guide-to-written-exam.pdf) 

A MOOC: [Intro to Actuarial Science](https://www.edx.org/course/introduction-actuarial-science-anux-anu-actuarialx-1)

[An open-resource text](https://diginole.lib.fsu.edu/islandora/object/fsu:717221)

[Desmos](https://www.desmos.com/): An online graphing and scientific calculator

---

**Lecture notes and the like**

[Materials on R](https://mcudina.github.io/rbook/)

---

**A few "shortcuts" for R and RStudio**

Here are some resources I created for *Applied Statistics*. They will be useful in this course as well and can be used in conjunction with our lecture notes. 

[R (main website)](https://www.r-project.org/)

[RStudio (main website)](https://rstudio.com/)

[The instructions slideshow](instructions/m358k-R-instructions.html)

[The basic R slideshow](instructions/m358k-basic-R.html)

[The basic R "cheatsheet"](https://raw.githubusercontent.com/rstudio/cheatsheets/master/base-r.pdf)

[If ... else](https://www.datamentor.io/r-programming/if-else-statement/)

[A tutorial on functions in R](https://www.tutorialspoint.com/r/r_functions.htm)

---

**Class 1: January 9th**<br>
Orientation. <br>

[A role model](pics/bilbo.jpeg)

[First-Day Handout](syllabus/syllabus-54720.pdf)

[Day-by-day](notes/m339d-spring-2023-todo.pdf)

[Funny](http://books.google.com/books?id=8FgF3dOoUVsC&lpg=PA49&ots=UU208Gu6pv&dq=pigg%20vioos&pg=PA49#v=onepage&q=pigg%20vioos&f=false)

[Important prerequisite topics](lectures/m339d-prerequisite-topics.pdf): A checklist of the prerequisite material. 

---

**Class 2: January 11th**<br>
Setting up R and RStudio. Basics of R: Arithmetic. Vectors. R-scripts and R-notebooks.<br>

[Console printout](notes/console.txt)

[The R-script from class](code/first-script.R)

[The R-notebook from class](code/first-notebook.Rmd)

[Homework #1: Part #2](hw/m339d-hw1-prereq.pdf) -- **due on Friday, January 20th**

---

**Class 3: January 13th**<br>
`For` loops.<br> 

[Problem Set #1](code/m339d-ps1.Rmd):  **Problems**

[Problem Set #1](code/m339d-ps1-in-class.Rmd): **Solutions from class**

Functions in R. `If ... else` in R.<br> 

[The R-script from class](code/ftions-ifelse.R)

Background. 

[Lecture One](lectures/m339d-lecture-one-background.pdf): Background.

Prerequisite review.<br>

[Problem Set #2](problem-sets/m339d-ps2-prereq.pdf):  **Problems**

[Class notes](notes/m339d-jan-13-2023.pdf) 

---

**Class 4: January 18th**<br>
Prerequisite review [cont'd]. Standing assumptions and conventions. Risky assets. <br>

[Class notes](notes/m339d-jan-18-2023.pdf) 

[Problem Set #2](problem-sets/m339d-ps2-prereq-solns.pdf): **Solutions**

[Homework #2](hw/m339d-hw2-prereq.pdf) -- **due on Friday, January 27th**

<!--
[Duke gpa](data/gpa.csv) - courtesy of OpenCourse Statistics

[The R-notebook for class](code/m339d-gpa-probs.Rmd)

[The R-notebook from class](code/m339d-gpa-solns.Rmd)
-->
---

**Class 5: January 20th**<br>
Transaction costs. <br>

<!--
[More class notes](notes/m339d-jan-25-2021.pdf) 
-->

[Lecture Two](lectures/m339d-lecture-two-transaction-costs.pdf): Transaction Costs

[Lecture Three](lectures/m339d-lecture-three-standing-assumptions-conventions.pdf): Standing Assumptions and conventions

Outright purchase. Short sales.<br>

[Investopedia](https://www.investopedia.com/ask/answers/05/marginaccountshortsell.asp): On margin accounts for short sales

[Class notes](notes/m339d-jan-20-2023.pdf)

[Working directory in `R`](https://r-coder.com/working-directory-r/)

[Homework #1](hw/m339d-hw1-prereq-solns.pdf) -- **solutions**

---

**Class 6: January 23rd**<br>
Historical returns of stocks.<br>

[Yahoo! Finance](https://finance.yahoo.com)

[Wikipedia](https://en.wikipedia.org/wiki/Stock_market_index): Stock market index

[The R-notebook for class](code/m339d-msft-probs.Rmd)

[The Normal Distribution](http://demonstrations.wolfram.com/TheNormalDistribution/) from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Ian McLeod 

[Class notes](notes/m339d-jan-23-2023.pdf)

[The R-notebook from class](code/m339d-msft-probs-4.Rmd)

[Time plots in `R`](https://www.geeksforgeeks.org/draw-multiple-time-series-in-same-plot-in-r/)

[Project #1](projects/m339d-project1-probs.pdf) -- **due on Monday, February 6th, 2023**

[Project #1](code/m339d-project1-probs.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your project 

---

**Class 7: January 25th**<br>
Payoff and profit.<br>

[Class notes](notes/m339d-jan-25-2023.pdf) 

---

**Class 8: January 27th**<br>
Payoff and profit curves. Long/short positions.<br>

[Class notes](notes/m339d-jan-27-2023.pdf) 

[Homework #2](hw/m339d-hw2-prereq-solns.pdf) -- **solutions**

[Homework #3](hw/m339d-hw3.pdf) -- **due on Friday, February 3rd**

---

**Class 9: January 30th**<br>
Basic risk management. Forward contracts.<br>

[Problem Set #3](problem-sets/m339d-ps3-forwards-inspiration.pdf):  **Problems**

[Problem Set #3](problem-sets/m339d-ps3-forwards-inspiration-solns.pdf):  **Solutions**

[Class notes](notes/m339d-jan-30-2023.pdf) 

---

**Class 10: February 1st**<br>
<span style="color: blue;">**Asynchronous work due to winter conditions.**</span>
<br>

[The R-notebook for class](code/m339d-project1-variation.Rmd): **Problems**

[The R-notebook for class](code/m339d-project1-variation-solns.Rmd): **Solutions**

---

**Class 11: February 3rd**<br>
<span style="color: blue;">**Asynchronous work due to winter conditions.**</span>
<br>

[Lecture Four](lectures/m339d-lecture-four-payoff-profit.pdf): Initial cost, payoff and profit (the simplest case).

[Wikipedia](http://en.wikipedia.org/wiki/Hedge_(finance)): Hedging

[Lecture Five](lectures/m339d-lecture-five-basic-risk-management-forwards.pdf): Basic risk management. Forwards.

---

**Class 12: February 6th**<br>
Forward contracts [practice].<br>

[Class notes](notes/m339d-feb-06-2023.pdf) 

---

**Class 13: February 8th**<br>
Hedging using forward contracts.<br>

[Problem Set #4](problem-sets/m339d-ps4-forwards.pdf):  **Problems**

[Problem Set #4](problem-sets/m339d-ps4-forwards-solns.pdf):  **Solutions**

[Homework #4](hw/m339d-hw4-forwards.pdf) -- **due on Friday, February 17th**

European call options.<br>

[Lecture Six](lectures/m339d-lecture-six-European-calls.pdf): European call options.

[Class notes](notes/m339d-feb-08-2023.pdf) 

[In-Term One](exams/m339d-one-topics.pdf): Topics

[Practice for In-Term One](exams/m339d-one-sample-probs.pdf) -- **problems** 

[Practice for In-Term One](exams/m339d-one-sample-solns.pdf) -- **solutions** 

---

**Class 14: February 10th**<br>
More on European call options.<br>

[Problem Set #5](problem-sets/m339d-ps5-calls.pdf):  **Problems**

[Class notes](notes/m339d-feb-10-2023.pdf) 

[Homework #3](hw/m339d-hw3-solns.pdf) -- **solutions**

[Homework #5](hw/m339d-hw5-calls.pdf) -- **due on Friday, February 24th**

---

**Class 15: February 13th**<br>
Even more on European call options.<br>

[Class notes](notes/m339d-feb-13-2023.pdf) 

[Problem Set #5](problem-sets/m339d-ps5-calls-solns.pdf):  **Solutions**

[Notes](notes/m339d-convexity.pdf): Convexity of functions - **useful for the last problem in the project**

[Dow data](data/dow.csv)

[Dow futures data](data/dow-futures.csv)

[Apple call data](data/apple-calls.csv)

[Project #2](projects/m339d-project2-probs.pdf) -- **due on Monday, February 27th, 2023**

[Project #2](projects/m339d-project2-probs.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your project 

---
 
**Class 16: February 15th**<br>
<span style="color: red;">**In-Term One**</span><br>

[In-Term One](exams/m339d-one.pdf) -- **problems** 

[In-Term One](exams/m339d-one-solns.pdf) -- **solutions** 

---

**Class 17: February 17th**<br>
European put options. Moneyness.<br>

[Lecture Seven](lectures/m339d-lecture-seven-puts.pdf): European put options. Moneyness.

[Problem Set #6](problem-sets/m339d-ps6-puts.pdf):  **Problems**

[Class notes](notes/m339d-feb-17-2023.pdf) 

[Homework #4](hw/m339d-hw4-forwards-solns.pdf) -- **solutions**

---

**Class 18: February 20th**<br>
Put option practice.<br>

[Problem Set #6](problem-sets/m339d-ps6-puts-solns.pdf):  **Solutions**

[Homework #6](hw/m339d-hw6-puts.pdf) -- **due on Friday, March 3rd**

**(Enrichment material)** [Lecture Eight](lectures/m339d-lecture-eight-collars-hedging.pdf): Collars.

Finite probability spaces [revisited]. Arbitrage portfolios.<br>

[Class notes](notes/m339d-feb-20-2023.pdf) 

**(Enrichment material)** [Lecture Nine](lectures/m339d-lecture-nine-derivative-securities.pdf): Derivative securities.

**(Interesting reading)** [Employee stock options](http://en.wikipedia.org/wiki/Employee_stock_option)

**(Interesting reading)** [Life Assurance Act (1774)](http://en.wikipedia.org/wiki/Life_Assurance_Act_1774)

---

**Class 19: February 22nd**<br>
Law of the Unique Price. Derivative securities. Replicating portfolios.<br>

[Class notes](notes/m339d-feb-22-2023.pdf) 

**(Enrichment material)** [Lecture Ten](lectures/m339d-lecture-ten-forwards-pricing.pdf): Pricing prepaid forwards and forwards on stocks.

---

**Class 20: February 24th**<br>
Equity-linked contracts.<br>

[Problem packet](problem-sets/m339d-equity-linked.pdf)

[Class notes](notes/m339d-feb-24-2023.pdf) 

---

**Class 21: February 27th**<br>
Put-call parity.<br>

[Problem packet](problem-sets/m339d-parity-no-div.pdf)

<!--
[Class notes](notes/m339d-oct-17-2022.pdf) 
-->

**(Enrichment material)** [Lecture Eleven](lectures/m339d-lecture-eleven-put-call-parity.pdf): Put-call Parity with dividends. 

Chooser options.<br>

[Problem packet](problem-sets/m339d-chooser.pdf)

**(Enrichment material)** [Lecture Twelve](lectures/m339d-lecture-twelve-gap-options.pdf): Gap options.

**(Enrichment material)** [Lecture Thirteen](lectures/m339d-lecture-13-exchange-options.pdf): Exchange options

**(Enrichment material)** [Lecture Fourteen](lectures/m339d-lecture-14-bounds-bull-spreads.pdf): Call/put-price bounds. Bull spreads.

**(Enrichment material)** [Lecture Fifteen](lectures/m339d-lecture-15-convexity-butterfly.pdf): Call-price convexity.

---

**Class 22: March 1st**<br>
Random number generation.<br>

[Wikipedia](https://en.wikipedia.org/wiki/Random_number_generation): Random number generation

[Wikipedia](https://en.wikipedia.org/wiki/Mersenne_Twister): Mersenne twister

[An atmospheric RNG](https://www.random.org/)

The Strong Law of Large Numbers. Monte Carlo simulation.<br>

<!--
[Class notes](notes/m339d-oct-19-2022.pdf) 
-->

[Problem Set #7](problem-sets/m339d-ps7-mc.Rmd)

<!--
[Problem Set #7](problem-sets/m339d-ps7-mc-solns.Rmd): **Solutions**
-->

[Apple put data](data/apple-puts.csv)

[Project #3](projects/m339d-project3-probs.pdf) -- **due on Monday, March 27th**

[Project #3](projects/m339d-project3-probs.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your project 

---

**Class 23: March 3rd**<br>
The binomial asset-pricing model. Historical returns of stocks. Forward trees. <br>

<!--
[Class notes](notes/m339d-oct-21-2022.pdf) 
-->

**(Enrichment material)** [Lecture Sixteen](lectures/m339d-lecture-16-binomial-asset-pricing.pdf): The binomial asset-pricing model with continuous dividends.

[Homework #7](hw/m339d-hw7-parity.pdf) -- **due on Friday, March 10th**

---

**Class 24: March 6th**<br>
Binomial option pricing: Pricing by replication. <br>

[Problem Set #8](problem-sets/m339d-ps8-bin-pricing.pdf): **Problems**

<!--
[Class notes](notes/m339d-oct-26-2022.pdf) 

[Problem Set #6](problem-sets/m339d-ps6-bin-pricing-solns.pdf): **Solutions**
-->

Binomial option pricing: Risk-neutral probability. <br>

<!--
[Class notes](notes/m339d-oct-28-2022.pdf) 
-->

[Homework #8](hw/m339d-hw8-one-period.pdf) -- **due on Friday, March 24th**

**(Enrichment material)** [Lecture Seventeen](lectures/m339d-lecture-17-binomial-option-pricing-one-period.pdf): Binomial option pricing with continuous dividends.


---

**Class 25: March 8th**<br>
Binomial option pricing: Two periods.

[Problem Set #9](problem-sets/m339d-ps9-two-periods.pdf): **Problems**

<!--
[Class notes](notes/m339d-oct-31-2022.pdf) 

[Problem Set #9](problem-sets/m339d-ps9-two-periods-solns.pdf): **Solutions**
-->

Multiple binomial periods. <br>

<!--
[Class notes](notes/m339d-nov-02-2022.pdf) 
-->

[Homework #9](hw/m339d-hw9-binom.pdf) -- **due on Friday, March 31st**

---

**Class 26: March 10th**<br>
Monte Carlo for binomial option pricing. <br>

[Problem Set #10](problem-sets/m339d-ps10-binomial-mc-probs.Rmd)

---

**Class 27: March 20th**<br>
Review of the normal distribution.<br>

[Homework #10](hw/m339d-hw10-normal.pdf) -- **due on Friday, April 7th**

---

**Class 28: March 22nd**<br>
<span style="color: red;">**In-Term Two**</span><br>

---

**Class 29: March 24th**<br>
The normal approximation to the binomial.<br>

[Standard normal table](notes/std-normal-table.pdf)

[Open Intro Stats Video](https://youtu.be/VvksxAZAlrQ): The normal approximation to the binomial. 

[Problem Set #11](problem-sets/m339d-ps11-dML.pdf): **Problems**

<!--
[Class notes](notes/m339d-nov-11-2022.pdf) 

[Problem Set #11](problem-sets/m339d-ps11-dML-solns.pdf): **Solutions**
-->

[Apple parity](data/apple-parity.csv)

[Project #4](projects/m339d-project4-probs.pdf) -- **due on Monday, April 24th**

[Project #4](projects/m339d-project4-probs.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your project 

---

**Class 30: March 27th**<br>
The limiting behavior of stock prices. More on realized returns.<br> 

[Mathematica Code](code/m339d-binomial-tree-limit.nb): Binomial model limit 

<!--
[Class notes](notes/m339d-nov-14-2022.pdf) 
-->

---

**Class 31: March 29th**<br>
Moment generating functions. The log-normal distribution. Jensen's inequality.<br>

[Lecture notes](lectures/m339w-lognormal.pdf): The lognormal distribution

<!--
[Class notes](notes/m339w-feb-09-2022.pdf): mgf. The log-normal distribution. Jensen's inequality.
-->

[The Log Normal Distribution](http://demonstrations.wolfram.com/TheLogNormalDistribution/){.demonstrationHyperlink}
from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Chris Boucher 

[Mathematica demonstration](http://demonstrations.wolfram.com/ModelingReturnDistributions/): Modeling return distributions

---

**Class 32: March 31st**<br>
Log-normal stock prices: Parameter interpretation.<br>

<!--
[Class notes](notes/m339w-feb-11-2022.pdf): Lognormal stock prices: Mean. Median. 
-->

**(Enrichment material)** [Lecture notes](lectures/m339w-on-pricing.pdf): On pricing in the Black-Scholes model with continuous dividends. 

---

**Class 33: April 3rd**<br>
Log-normal stock prices: Tail probabilities.<br>

<!--
[Class notes](notes/m339w-feb-16-2022.pdf): Tail probabilities.
-->

---

**Class 34: April 5th**<br>
Log-normal stock prices: Partial expectation.<br>

<!--
[Class notes](notes/m339w-feb-21-2022.pdf): Partial expectation. Conditional expectation.
-->

---

**Class 35: April 7th**<br>
The Black-Scholes pricing formula.<br>

[Problem Set #12](problem-sets/m339d-ps12-BS.pdf): **Problems**

<!--
[Class notes](notes/m339d-nov-16-2022.pdf) 

[Class notes](notes/m339d-nov-18-2022.pdf) 

[Problem Set #12](problem-sets/m339d-ps12-BS-solns.pdf): **Solutions**
-->

[Problem](problem-sets/mfe-sp2007-p8.pdf)

[Homework #11](hw/m339d-hw11-BS.pdf) -- **due on Friday, April 14th**

---

**Class 36: April 10th**<br>
Forward-start options. Rolling insurance strategy.<br>

---

**Class 37: April 12th**<br>
Focus on the delta.<br>

[Problem](problem-sets/m339d-ifm-delta.pdf)

---

**Class 38: April 14th**<br>
Delta-hedging. <br>

[Problem](problem-sets/m339d-ifm-delta-hedge.pdf)

---

**Class 39: April 17th**<br>
Monte Carlo with Black-Scholes pricing. <br>

[Problem Set #13](problem-sets/m339d-ps13-BS-mc.Rmd)



<!--
Expected return of a portfolio.<br>

[Problem](problem-sets/m339d-ifm-exp-return.pdf)

[Class notes](notes/m339d-sept-12-2022.pdf) 

Volatility of a portfolio. Diversification. Market indices. <br>

[Problems](problem-sets/m339d-vol.pdf)

[Class notes](notes/m339d-sept-14-2022.pdf) 

Feasible sets. Efficient portfolios. Effect of correlation. <br>

[Problems](problem-sets/m339w-vol.pdf)

[Class notes](notes/m339d-sept-16-2022.pdf) 

[Mathematica demonstration](http://demonstrations.wolfram.com/TwoAssetMarkowitzFeasibleSet/): A Two-Asset Markowitz Feasible Set 

[Mathematica demonstration](http://demonstrations.wolfram.com/ThreeAssetEfficientFrontier/): A Three-Asset Feasible Set and Efficient Frontier 

[Problem](problem-sets/m339d-ifm-efficient.pdf)

[September survey](surveys/m339d-sept-survey.docx)

Sharpe ratio.<br>

[Class notes](notes/m339d-sept-19-2022.pdf) 

[Problem](problem-sets/m339d-ifm-sharpe.pdf)

The Capital Asset Pricing Model (CAPM).<br>

[Class notes](notes/m339d-sept-21-2022.pdf) 

[Problem packet](problem-sets/m339d-required-returns.pdf)

[Homework #3](hw/m339d-hw3-intro-corp-finance.pdf) -- **due on Monday, October 3rd**

[Class notes](notes/m339d-sept-26-2022.pdf) 

[Homework #4](hw/m339d-hw4-corp-finance-solns.pdf) -- **solutions**

---
***
---

[In-Term Two](exams/m339d-two-topics.pdf): Topics

[Practice for In-Term Two](exams/m339d-two-sample-probs.pdf): Problems

[Practice for In-Term Two](exams/m339d-two-sample-solns.pdf): Solutions

[In-Term Two](exams/m339d-two-solns.pdf) -- **solutions** 







[Project #5](projects/m339d-project5-probs.pdf) -- **due on December 2nd, 2022**

[Project #5](projects/m339d-project5-probs.Rmd) - this is the Rmd file which you are more than welcome to use to neatly complete your project 

[Problem Set #11](problem-sets/m339d-ps11-BS-mc-in-class.Rmd) - **the partial solution**


Implied volatility. <br>

[Problem](problem-sets/m339d-ifm-impl-vol.pdf)

[Problem Set #11](problem-sets/m339d-ps11-BS-mc-in-class-contd.Rmd) - **the complete solution**

[Class notes](notes/m339d-nov-28-2022.pdf) 

[In-Term Three](exams/m339d-three-topics.pdf): Topics

[Practice for In-Term Three](exams/m339d-three-sample.pdf) -- **problems** 

[Practice for In-Term Three](exams/m339d-three-sample-solns.pdf) -- **solutions** 

---

**Class 40: November 30th**<br>
Problem-solving session. <br>

[Class notes](notes/m339d-nov-30-2022.pdf) 

[Homework #8](hw/m339d-hw8-BS-solns.pdf) -- **solutions**

---

**Class 41: December 2nd**<br>
Problem-solving session. <br>

[Class notes](notes/m339d-delta-hedging.pdf) 

---

**Class 42: December 5th**<br>
<span style="color: red;">**In-Term Three**</span><br>

[In-Term Three](exams/m339d-three-solns.pdf) -- **solutions**

---

[The Final Exam](exams/m339d-final-topics.pdf): Topics

[Delta-Hedging Practice](exams/m339d-final-practice.pdf) -- **problems** 

[Delta-Hedging Practice](exams/m339d-final-practice-solns.pdf) -- **solutions** 

<!--

[Quiz #1](quizzes/m339d-quiz-one.pdf) -- **due on Friday, January 21st** 

---

[Quiz #1](quizzes/m339d-quiz-one-solns.pdf) -- **solutions** 

[Quiz #2](quizzes/m339d-quiz-two.pdf) -- due on **Monday, January 24th**

---

Outright purchase. Short sales. Discrete-dividend-paying stocks. <br>

[Class notes](notes/m339d-jan-24-2022.pdf): Outright purchase. Short sales. Discrete-dividend-paying stocks. 

[Quiz #2](quizzes/m339d-quiz-two-solns.pdf) -- **solutions**

[Quiz #3](quizzes/m339d-quiz-three.pdf) -- **due on Wednesday, January 26th**

---

Foreign currencies.<br>

[Class notes](notes/m339d-jan-26-2022.pdf): Outright purchase of stocks. Foreign currencies. 

[Quiz #3](quizzes/m339d-quiz-three-solns.pdf) -- **solutions**

[Quiz #4](quizzes/m339d-quiz4.pdf) -- **due on Monday, January 31st**

---

Continuous dividends. Market indices. <br>

[Class notes](notes/m339d-jan-28-2022.pdf): 
Continuous-dividend-paying stocks.

[Problem Set #3](problem-sets/m339d-ps-three-cont-div.pdf): **Problems**

[Problem Set #3](problem-sets/m339d-ps-three-cont-div-solns.pdf): **Solutions**

[Quiz #5](quizzes/m339d-quiz5-cont-div.pdf) -- **due on Wednesday, February 2nd**

[Homework #1](hw/m339d-hw-one-prereq-trans-costs-solns.pdf) -- **solutions**

---

Static portfolios.<br>

[Class notes](notes/m339d-jan-31-2022.pdf): Static portfolios. Initial cost. Payoff. Profit.

---

Static portfolios [cont'd]. Payoff and profit curves. Long/short positions. <br>

[Class notes](notes/m339d-feb-02-2022.pdf): Static portfolios [cont'd].

[Quiz #5](quizzes/m339d-quiz5-cont-div-solns.pdf) -- **solutions**

---

More on short sales.<br>

[Class notes](notes/m339d-feb-10-2021.pdf): Short sales. 

[Problem Set #4](problem-sets/m339d-ps-four-short-sales.pdf): **Problems**

[Problem Set #4](problem-sets/m339d-ps-four-short-sales-solns.pdf): **Solutions**

[Quiz #6](quizzes/m339d-quiz6-trans-short-sales.pdf) -- **due on Monday, February 7th**

---

Fully-leveraged purchase. Basic risk management. Forward contracts.<br>

[Class notes](notes/m339d-feb-07-2022.pdf): Fully-leveraged purchase. Basic risk management. Forwards.

[Quiz #6](quizzes/m339d-quiz6-trans-short-sales-solns.pdf) -- **solutions**

[Quiz #7](quizzes/m339d-quiz7-leveraging.pdf) -- **due on Wednesday, February 9th**

[Quiz #8](quizzes/m339d-quiz8-two-assets.pdf) -- **due on Monday, February 14th**

---

[Problem Set #5](problem-sets/m339d-ps-five-yuri-one.pdf): **Problems**

[Problem Set #5](problem-sets/m339d-ps-five-yuri-one-solns.pdf): **Solutions**

[Problem Set #6](problem-sets/m339d-ps-six-yuri-two.pdf): **Problems**

[Problem Set #6](problem-sets/m339d-ps-six-yuri-two-solns.pdf): **Solutions**

---

Hedging using forward contracts.<br>

[Class notes](notes/m339d-feb-09-2022.pdf): More on forwards.

[Additional class notes](notes/m339d-extra-forward-hedging.pdf): User/buyer of goods hedging using a forward.

[Problem Set #7](problem-sets/m339d-ps-seven-forwards-hedging.pdf): **Problems**

[Problem Set #7](problem-sets/m339d-ps-seven-forwards-hedging-solns.pdf): **Solutions**

[Quiz #7](quizzes/m339d-quiz7-leveraging-solns.pdf) -- **solutions**

[Quiz #9](quizzes/m339d-quiz9-forwards.pdf) -- **due on Wednesday, February 16th**

---

[Class notes](notes/m339d-feb-11-2022.pdf): European calls. 

---

Caps. Covered option writing. European put options.<br>

[Class notes](notes/m339d-feb-14-2022.pdf): Covered/naked option writing. European put options.

[Quiz #8](quizzes/m339d-quiz8-two-assets-solns.pdf) -- **solutions**

[Quiz #10](quizzes/m339d-quiz10-calls.pdf) -- **due on Monday, February 28th**

[Homework #4](hw/m339d-hw4-forwards-calls.pdf) -- **due on Friday, March 4th**

---

Floors. Covered puts. Moneyness. American and Bermudan options.<br>

[Class notes](notes/m339d-feb-16-2022.pdf): European put options [review]. Floors. Covered puts. Moneyness. American and Bermudan options.

[Problem Set #8](problem-sets/m339d-ps-eight-forwards-calls-puts-probs.pdf): **Problems**

[Problem Set #8](problem-sets/m339d-ps-eight-forwards-calls-puts-solns.pdf): **Solutions**

**Suggested problems:** Sample SoA problems (IFM exam: Derivatives: Intro): \#12, \#26, \#35, \#48, \#49, \#61, \#62, \#66, \#75 (European put options, moneyness)

[Quiz #9](quizzes/m339d-quiz9-forwards-solns.pdf) -- **solutions**

---

Collars. Derivative securities.<br>

[Class notes](notes/m339d-feb-18-2022.pdf): Collars. Derivative securities. 

**Suggested problems:** Sample SoA problems (IFM exam: Derivatives: Introductory): #24 (rationale for the existence of derivatives)

[Quiz #11](quizzes/m339d-quiz11.pdf) -- **due on Wednesday, March 2nd**

---

Dynamic portfolios. Finite probability spaces.<br>

[Class notes](notes/m339d-feb-21-2022.pdf): Arbitrage portfolios. Law of the Unique Price. Replicating portfolios.

[Homework #5](hw/m339d-hw5-calls-puts.pdf) -- **due on Friday, March 11th**

---

Arbitrage portfolios. Law of the Unique Price. Replicating portfolios.<br>

[Class notes](notes/m339d-feb-23-2022.pdf): Arbitrage portfolios. Law of the Unique Price. Replicating portfolios.


---

Pricing prepaid forwards and forwards on stocks.<br>

[Problem packet](problem-sets/m339d-forwards-futures.pdf)

[Class notes](notes/m339d-feb-25-2022.pdf): Pricing prepaid forwards and forwards on stocks.

**Suggested problems**: Sample SoA problems (IFM: Derivatives: Introductory): #20, #21, #29

[Quiz #12](quizzes/m339d-quiz12-parity-prep.pdf) -- **due on Monday, March 7th**

---

More on synthetic forwards. Futures.<br>


[Class notes](notes/m339d-feb-28-2022.pdf): Synthetic forwards. Futures.

**Suggested problems:** Sample SoA problems (IFM exam: Derivatives: Introductory): #30, #32, #45, #69 (futures)

[Quiz #10](quizzes/m339d-quiz10-calls-solns.pdf) -- **solutions**

---

Put-call parity.<br>

[Class notes](notes/m339d-mar-02-2022.pdf): Put-call parity.

[Quiz #11](quizzes/m339d-quiz11-solns.pdf) -- **solutions**

[Quiz #13](quizzes/m339d-quiz13-parity.pdf) -- **due on Wednesday, March 9th**

---

[Class notes](notes/m339d-mar-04-2022.pdf): Synthetic forwards (revisited). Chooser options. 

[Homework #4](hw/m339d-hw4-forwards-calls-solns.pdf) -- **solutions**

---

Gap options.<br>

[Lecture Twelve](lectures/m339d-lecture-twelve-gap-options-empty.pdf): Gap options (skeleton).


[Class notes](notes/m339d-mar-07-2022.pdf): Equity-linked contracts. Gap options.

[Quiz #12](quizzes/m339d-quiz12-parity-prep-solns.pdf) -- **solutions**

[Quiz #14](quizzes/m339d-quiz14-gaps.pdf) - **due on Monday, March 21st**

---

Options on currencies.<br>

[Class notes](notes/m339d-mar-09-2022.pdf): Currency options.

[Quiz #13](quizzes/m339d-quiz13-parity-solns.pdf) -- **solutions**

---

Exchange options.<br>

[Problem](problem-sets/m339d-mfe-2007-p6.pdf)

[Class notes](notes/m339d-mar-11-2022.pdf): Exchange options. Generalized put-call parity.

[Homework #5](hw/m339d-hw5-calls-puts-solns.pdf) -- **solutions**

[Quiz #15](quizzes/m339d-quiz15-exchange.pdf) - **due on Wednesday, March 23rd**

[Quiz #16](quizzes/m339d-quiz16-exchange-exp.pdf) - **due on Monday, March 28th**

Bounds on option prices.<br>

[Class notes](notes/m339d-mar-21-2022.pdf): Bounds on call prices.

[Quiz #14](quizzes/m339d-quiz14-gaps-solns.pdf) - **solutions**

---

Bounds on put prices. Monotonicity of call prices. Bull spreads. <br>

[Class notes](notes/m339d-mar-23-2022.pdf): Bounds on put prices. Monotonicity of call prices. Bull spreads.

[Quiz #15](quizzes/m339d-quiz15-exchange-solns.pdf) - **solutions**

---

Monotonicity of put prices. "Cord-slope" bounds. Bear spreads.<br>

[Problem](problem-sets/m339d-properties.pdf)

[Class notes](notes/m339d-mar-25-2022.pdf): Monotonicity of put prices. "Cord-slope" bounds. Bear spreads. 

[Homework #6](hw/m339d-hw6-parity-solns.pdf) -- **solutions**

---

No class. Instructor ill.<br>

[Quiz #16](quizzes/m339d-quiz16-exchange-exp-solns.pdf) - **solutions**

[In-Term Two](exams/m339d-two.pdf) -- **problems** 

---

Convex functions. Convexity of put/call prices. Butterfly spreads.<br>

[Class notes](notes/m339d-mar-30-2022.pdf): Convexity of call prices. Butterfly spreads.

---

Put-price convexity. Butterfly-spread practice.<br> 

[Problem packet](problem-sets/m339d-butterflies.pdf)

[Class notes](notes/m339d-apr-01-2022.pdf): Put-price convexity. More on butterfly spreads. 

---

Straddles. Strangles.<br>

[Class notes](notes/m339d-apr-04-2022.pdf): Speculating on volatility. Collars revisited. 

**Suggested problems**: Sample SoA problems (IFM exam: Derivatives: Introductory): #8, #16 Sample SoA problems (IFM exam: Derivatives: Advanced): #40 (spreads, strangles, straddles)

[Quiz #17](quizzes/m339d-quiz17-properties.pdf) - **due on Wednesday, April 6th**

[Homework #7](hw/m339d-hw7-price-properties.pdf) - **due on Friday, April 8th**

[Quiz #18](quizzes/m339d-quiz-thirteen-straddles.pdf) - **due on Monday, April 11th**


---

More on collars. Ratio spreads. Box spreads.<br>

[Problem packet](problem-sets/m339d-collar-ratio-box.pdf)

[Class notes](notes/m339d-apr-06-2022.pdf): More on collars. Ratio spreads. Box spreads. 

[Quiz #17](quizzes/m339d-quiz17-properties-solns.pdf) - **solutions**

[Quiz #19](quizzes/m339d-quiz19-box-ratio.pdf) - **due on Wednesday, April 13th**

---

The binomial asset-pricing model. 

[Homework #8](hw/m339d-hw8.pdf) - **due on Friday, April 15th**

Binomial option pricing: Pricing by replication. 

[Problem Set #9](problem-sets/m339d-ps-nine-bin-pricing.pdf): **Problems**

[Class notes](notes/m339d-apr-08-2022.pdf): The binomial asset-pricing model.

---

Binomial option pricing [cont'd].<br> 

[Class notes](notes/m339d-apr-11-2022.pdf): Pricing by replication. Risk-neutral probability.

[Homework #7](hw/m339d-hw7-price-properties-solns.pdf) - **solutions**

[Quiz #18](quizzes/m339d-quiz-thirteen-straddles-solns.pdf) - **solutions**

[Quiz #20](quizzes/m339d-quiz20-delta-B.pdf) - **due on Monday, April 18th**

[Quiz #21](quizzes/m339d-quiz21-binomial.pdf) - **due on Wednesday, April 20th**

---

Binomial option pricing: Graphical interpretation.<br>

[Class notes](notes/m339d-apr-13-2022.pdf): Binomial option pricing practice. Graphical interpretation of a call's replicating portfolio.

[Problem Set #9](problem-sets/m339d-ps-nine-bin-pricing-solns.pdf): **Solutions**

[Quiz #19](quizzes/m339d-quiz19-box-ratio-solns.pdf) - **solutions**

---

Binomial option pricing: The forward tree.<br>

[Lecture Eighteen](lectures/m339d-lecture-18-forward-trees.pdf): Forward trees.

[Class notes](notes/m339d-apr-15-2022.pdf): The forward tree. 

[Problem Set #10](problem-sets/m339d-ps-ten-two-periods.pdf) -- **problems**

[Homework #8](hw/m339d-hw8-solns.pdf) - **solutions**

[Homework #9](hw/m339d-hw9-one-period.pdf) - **due on Friday, April 22nd**

---

Binomial option pricing: Two periods.<br>

[Class notes](notes/m339d-apr-18-2022.pdf): Two periods.

[Problem Set #10](problem-sets/m339d-ps-ten-two-periods-solns.pdf) -- **solutions**

[Quiz #20](quizzes/m339d-quiz20-delta-B-solns.pdf) - **solutions**

---

Multiple binomial periods. Early exercise (revisited).<br>

[Problem packet](problem-sets/m339d-early-exercise.pdf)

[Class notes](notes/m339d-apr-20-2022.pdf): Binomial option pricing (more periods). Early exercise.

[Quiz #21](quizzes/m339d-quiz21-binomial-solns.pdf) - **solutions**

[Quiz #22](quizzes/m339d-quiz22-Amer-binom-prep.pdf) - **due on Monday, April 25th**

---

Binomial pricing of American options. <br>

[Problem packet](problem-sets/m339d-american.pdf)

[Class notes](notes/m339d-apr-22-2022.pdf): Binomial pricing of American options.

**Suggested problems:** Sample IFM (Derivatives: Advanced) Problem \#44 (binomial pricing of American options)

[Homework #9](hw/m339d-hw9-one-period-solns.pdf) - **solutions**

[Homework #10](hw/m339d-hw10-binom.pdf) - **due on Friday, April 29th**

---

Binomial pricing of American option [practice].<br>

[Class notes](notes/m339d-apr-25-2022.pdf): Binomial pricing of American options (practice).

[Quiz #22](quizzes/m339d-quiz22-Amer-binom-prep-solns.pdf) - **solutions**

---

Properties of American-option prices. Asian options.<br>

[Class notes](notes/m339d-apr-27-2022.pdf): Bounds on American option prices. Definition of Asian options. 

**Suggested problems:** Sample IFM (Derivatives: Advanced) Problem \#26 (bounds on European and American option prices)

[Quiz #23](quizzes/m339d-quiz23-American.pdf) - **due on Thursday, April 28th**

[Quiz #24](quizzes/m339d-quiz24-Asian.pdf) - **due on Monday, May 2nd**

---

Asian-option pricing. Barrier options.<br>

[Class notes](notes/m339d-apr-29-2022.pdf): More on Asian options. Barrier options. 

[Slides](notes/m339d-barrier.pdf): Barrier options.

[Quiz #23](quizzes/m339d-quiz23-American-solns.pdf) - **solutions**

[Homework #10](hw/m339d-hw10-binom-solns.pdf) - **solutions**

---

Barrier options.<br>

[Problem packet](problem-sets/m339d-barrier.pdf)

[Class notes](notes/m339d-may-02-2022.pdf): More on barrier options. 

[Quiz #24](quizzes/m339d-quiz24-Asian-solns.pdf) - **solutions**

[Quiz #25](quizzes/m339d-quiz25-barrier.pdf) - **due on Wednesday, May 4th**

---

**Class 43: May 4th**<br>
Compound options.<br>

[Slides](notes/m339d-compound.pdf): Compound options.

[Homework #11](hw/m339d-hw11-exotic.pdf) - **not to be handed in**

Binomial pricing of options on currencies.<br>

[Problem](problem-sets/m339d-bin-currency.pdf)

[Class notes](notes/m339d-may-04-2022.pdf): Compound options. Currency options (the binomial model).

[Quiz #25](quizzes/m339d-quiz25-barrier-solns.pdf) - **solutions**

---

**Class 44: May 6th**<br>
Binomial pricing of options on futures contracts.<br>

[Problem](problem-sets/m339d-bin-futures.pdf)

[Class notes](notes/m339d-may-06-2022.pdf): Futures options (the binomial model). 

Problem-solving session.<br>

[Problem Set #11](problem-sets/m339d-ps11-currency-futures.pdf) -- **problems**

[Problem Set #11](problem-sets/m339d-ps11-currency-futures-solns.pdf) -- **solutions**

[Homework #11](hw/m339d-hw11-exotic-solns.pdf) - **solutions**

[In-Term Three](exams/m339d-three.pdf) -- **due on Wednesday, May 11th**


---

[In-Term One](exams/m339d-one-instructions.pdf): Instructions

[Mock In-Term One](exams/m339d-one-mock-probs.pdf) -- **Problems** 

[Mock In-Term One](exams/m339d-one-mock-solns.pdf) -- **Solutions** 

---

[In-Term Two](exams/m339d-two-instructions.pdf): Instructions

[Mock In-Term Two](exams/m339d-two-mock.pdf): **Problems** 

[Mock In-Term Two](exams/m339d-two-mock-solns.pdf): **Solutions** 

---

[In-Term Three](exams/m339d-three-instructions.pdf): Instructions

[Mock In-Term Three](exams/m339d-three-mock.pdf) -- **problems** 

[Mock In-Term Three](exams/m339d-three-mock-solns.pdf) -- **solutions** 

[In-Term Three](exams/m339d-three-histogram.pdf) -- **histogram** 

---

[An old prerequisite exam](m339d-sample-prereq.pdf) -- Problems

[An old prerequisite exam](m339d-sample-prereq-solns.pdf) -- Solutions
    
**The Prerequisite In-Term Exam**

[The prerequisite in-term exam](m339d-prereq.pdf) -- **Solutions**

---

[Problem set - **Problems**](m339d-ps-final-prep.pdf)
-   [Problem set - **Solutions**](m339d-ps-final-prep-solns.pdf)
-   [Problem set - **More problems**](m339d-ps-final-prep-sequel.pdf)
-   [Problem set - **Solutions to more
    problems**](m339d-ps-final-prep-sequel-solns.pdf)

-->






