---
title: "Introduction to Mathematical Statistics (M378K)"
output: html_document
---

<style>
  hr {
      position: relative; 
            top: 20px; 
            border: none; 
            height: 2px; 
            background: black; 
            margin-bottom: 50px; 
  }
</style>

---

**Important external links**

[Cornell Notes](http://lsc.cornell.edu/how-to-study/taking-notes/cornell-note-taking-system/): Advice on how to efficiently take written notes

[Lecture notes](https://web.ma.utexas.edu/users/gordanz/lecture_notes_page.html): Required reading for this course

---

**Class 1: January 12th, 2026**<br>
Orientation. <br>

[A role model](pics/bilbo.jpeg)

[First-Day Handout](syllabus/syllabus-57030.html)

[Lecture notes](https://web.ma.utexas.edu/users/gordanz/lecture_notes_page.html)

---

**Class 2: January 14th, 2026**<br>
Probability.<br> 

[Wikipedia](https://en.wikibooks.org/wiki/Set_Theory/Sets): Set notation

[Problem Set #1](problem-sets/m378k-ps1-omega-probs.pdf):  **Material we will work on in class**

[Class notes](notes/m378k-jan-14-2026.pdf)

[Problem Set #1](problem-sets/m378k-ps1-omega-solns.pdf):  **Solutions**

---

**Class 3: January 16th, 2026**<br>
Discrete random variables.<br>

[Problem Set #2](problem-sets/m378k-ps2-discrete-defn-probs.pdf):  **Material we will work on in class**

[Class notes](notes/m378k-aug-29-2025.pdf)

[Homework #1](hw/m378k-hw1-prereqs.pdf) -- **due on Friday, January 23rd, 2026**

---

**Class 4: January 21st, 2025**<br>
Conditional probability. Independence. More on discrete random variables.<br>

[Class notes](notes/m378k-jan-21-2026.pdf)

[Problem Set #2](problem-sets/m378k-ps2-discrete-defn-solns.pdf):  **Solutions**

---

**Class 5: January 23rd, 2026**<br>
Named discrete distributions.<br>

[Wikipedia](https://en.wikipedia.org/wiki/Binomial_theorem): The binomial theorem 

[Wikipedia](https://en.wikipedia.org/wiki/Pascal%27s_triangle): Pascal's triangle

[Mathematica demonstration](https://demonstrations.wolfram.com/BinomialProbabilityDistribution/): The binomial distribution

[Problem Set #3](problem-sets/m378k-ps3-discrete-probs.pdf):  **Problems we will work on in class**

[Class notes](notes/m378k-jan-23-2026.pdf)

[Mathematica demonstration](https://demonstrations.wolfram.com/GeometricDistribution/): The geometric distribution

[Homework #1](hw/m378k-hw1-prereqs-solns.pdf) -- **solutions**

[Homework #2](hw/m378k-hw2-discrete.pdf) -- **due on Friday, January 30th, 2026**

---

**Class 6: January 26th, 2026**<br>
<span style="color: purple;">**Iced in!**</span><br>

---

**Class 7: January 28th, 2026**<br>
The Poisson distribution.<br>

[Wikipedia](https://en.wikipedia.org/wiki/Poisson_distribution): The Poisson distribution

[Problem Set #3](problem-sets/m378k-ps3-discrete-solns.pdf):  **Solutions**

Expectation.<br>

[Problem Set #4](problem-sets/m378k-ps4-discrete-exp-var-probs.pdf):  **Problems we will work on in class**

[Class notes](notes/m378k-jan-28-2026.pdf)

---

**Class 8: January 30th, 2026**<br>
Variance. Continuous distributions.<br>

[Class notes](notes/m378k-jan-30-2026.pdf)

[Problem Set #4](problem-sets/m378k-ps4-discrete-exp-var-solns.pdf):  **Solutions**

[Homework #2](hw/m378k-hw2-discrete-solns.pdf) -- **solutions**

[Homework #3](hw/m378k-hw3-expectation-probs.pdf) -- **due on Friday, February 6th, 2026**


---

**Class 9: February 2nd, 2026**<br>
More on continuous distributions.<br>

[Problem Set #5](problem-sets/m378k-ps5-continuous-probs.pdf):  **Problems we will work on in class**

[Class notes](notes/m378k-feb-02-2026.pdf)

---

**Class 10: February 4th, 2026**<br>
The normal distribution. Expectation [the continuous case].<br>

[Standard Normal Distribution Areas](http://demonstrations.wolfram.com/StandardNormalDistributionAreas/){.demonstrationHyperlink} from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Ian McLeod 

[The Normal Distribution](http://demonstrations.wolfram.com/TheNormalDistribution/) from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Ian McLeod 

[Area of a Normal Distribution](http://demonstrations.wolfram.com/AreaOfANormalDistribution/){.demonstrationHyperlink} from the [Wolfram Demonstrations Project](http://demonstrations.wolfram.com/){.demonstrationHyperlink} by Eric Schulz 

[Class notes](notes/m378k-feb-04-2026.pdf)

[Problem Set #5](problem-sets/m378k-ps5-continuous-solns.pdf):  **Solutions**

---

[In-Term One](exams/m378k-one-topics.pdf): Topics

[Practice for In-Term One](exams/m378k-one-sample-probs.pdf) -- **problems** 

[Practice for In-Term One](exams/m378k-one-sample-solns.pdf) -- **solutions** 

---

**Class 11: February 6th, 2026**<br>
The cumulative distribution function (cdf).<br>

[Problem Set #6](problem-sets/m378k-ps6-cdf-probs.pdf):  **Problems we will work on in class**

[Class notes](notes/m378k-feb-06-2026.pdf)

<!--
[Problem Set #6](problem-sets/m378k-ps6-cdf-solns.pdf):  **Solutions**
-->

[Homework #3](hw/m378k-hw3-expectation-solns.pdf) -- **solutions**

---

**Class 12: February 9th, 2026**<br>
More on the cdf.<br>

[Problem Set #7](problem-sets/m378k-ps7-cdf-cont-probs.pdf):  **Problems we will work on in class**

[Standard normal table](notes/std-normal-table.pdf)

[`R` code on the normal](code/normal.R)

[Class notes](notes/m378k-feb-09-2026.pdf)

[Problem Set #7](problem-sets/m378k-ps7-cdf-cont-solns.pdf):  **Solutions**

---

**Class 13: February 11th, 2026**<br>
<span style="color: red;">**In-Term One**</span><br>

[In-Term One](exams/m378k-one-solns.pdf) -- **solutions** 

---

**Class 14: February 13th, 2026**<br>
Random vectors.<br>

[Class notes](notes/m378k-feb-13-2026.pdf)

<!--
[Homework #4](hw/m378k-hw4-random-vectors-probs.pdf) -- **due on Friday, October 3rd, 2025**
-->

---

**Class 15: February 16th, 2026**<br>
More on random vectors.<br>

<!--
[Class notes](notes/m378k-sept-29-2025.pdf)
-->

Independence. Transformations of random variables.<br>

[Problem Set #8](problem-sets/m378k-ps8-transformations-probs.pdf):  **Problems we will work on in class**

<!--
[Class notes](notes/m378k-oct-01-2025.pdf)
-->

More on transformations of random variables. The triangle distribution. The $\chi^2-$distribution.<br>

[Zed Statistics video](https://youtu.be/80ffqpZdKiA?si=qzwSLzEZOKbDlRc7): The $\chi^2-$ distribution. 

<!--
[Class notes](notes/m378k-oct-03-2025.pdf)

[Problem Set #8](problem-sets/m378k-ps8-transformations-solns.pdf):  **Solutions**

[Class notes](notes/m378k-oct-06-2025.pdf)

[Homework #4](hw/m378k-hw4-random-vectors-solns.pdf) -- **solutions**

[Homework #5](hw/m378k-hw5-transformations-probs.pdf) -- **due on Friday, October 10th, 2025**
-->

The $F-$distribution. Moment generating functions.<br>

[Problem Set #9](problem-sets/m378k-ps9-mgf-probs.pdf):  **Problems we will work on in class**

<!--
[Class notes](notes/m378k-oct-10-2025.pdf)

[Homework #5](hw/m378k-hw5-transformations-solns.pdf) -- **solutions**

[Homework #6](hw/m378k-hw6-mgf-probs.pdf) -- **due on Friday, October 17th, 2025**
-->

---
 
**Class 16: February 18th, 2026**<br>
More on the moment generating functions.<br>

<!--
[Class notes](notes/m378k-oct-13-2025.pdf)

[Problem Set #9](problem-sets/m378k-ps9-mgf-solns.pdf):  **Solutions**
-->

---

**Class 17: February 20th, 2026**<br>
More on the normal distribution.<br>

[Problem Set #10](problem-sets/m378k-ps10-normal-probs.pdf):  **Problems we will work on in class**

<!--
[Problem Set #10](problem-sets/m378k-ps10-normal-solns.pdf):  **Solutions**
-->


---

**Class 18: February 23rd, 2026**<br>
De Moivre-Laplace.<br>

[Problem Set #11](problem-sets/m378k-ps11-dML-probs.pdf):  **Problems we will work on in class**

[Mathematica demonstration](http://demonstrations.wolfram.com/IllustratingTheCentralLimitTheoremWithSumsOfBernoulliRandomV/): The Normal Approximation to the Binomial Distribution

[The R-script from class](code/dML-pres.R)

<!--
[Class notes](notes/m378k-oct-15-2025.pdf)

[Problem Set #11](problem-sets/m378k-ps11-dML-solns.pdf):  **Solutions**
-->


---

**Class 19: February 25th, 2026**<br>
The Central Limit Theorem.<br>

[Problem Set #12](problem-sets/m378k-ps12-clt-probs.pdf):  **Problems we will work on in class**

<!--
[Class notes](notes/m378k-oct-17-2025.pdf)

[Problem Set #12](problem-sets/m378k-ps12-clt-solns.pdf):  **Solutions**

[Homework #6](hw/m378k-hw6-mgf-solns.pdf) -- **solutions**
-->

---

**Class 20: February 27th, 2026**<br>
More on the $\chi^2-$distribution.<br>

[Mathematica demonstration: The Chi-Squared Distribution](http://demonstrations.wolfram.com/TheChiSquaredDistribution/)

[Mathematica demonstration: Tail Areas under the Chi-Squared Distribution](https://demonstrations.wolfram.com/TailAreasUnderChiSquaredDistributions/#embed)

[A $\chi^2-$table](notes/chi-squared-table-better.pdf)

The $\Gamma-$distribution.<br>

<!--
[Class notes](notes/m378k-oct-20-2025.pdf)
-->

[The R-script from class](code/gamma-clt.R)

<!--
[Homework #7](hw/m378k-hw7-gamma-probs.pdf) -- **due on Friday, October 31st, 2025**
-->

---

**Class 21: March 2nd, 2026**<br>
The statistical set-up. Order statistics.<br>

[Problem Set #13](problem-sets/m378k-ps13-order-stats-probs.pdf):  **Problems we will work on in class**

<!--
[Class notes](notes/m378k-oct-24-2025.pdf)

[Problem Set #13](problem-sets/m378k-ps13-order-stats-solns.pdf):  **Solutions**
-->

---

**Class 22: March 4th, 2026**<br>
Sampling distributions.<br>

[Problem Set #14](problem-sets/m378k-ps14-statistics-probs.pdf):  **Problems we will work on in class**

<!--
[Class notes](notes/m378k-oct-27-2025.pdf)

[Problem Set #14](problem-sets/m378k-ps14-statistics-solns.pdf):  **Solutions**

[In-Term Two](exams/m378k-two-topics.pdf): Topics

[Practice for In-Term Two](exams/m378k-two-sample-probs.pdf) -- **problems** 

[Practice for In-Term Two](exams/m378k-two-sample-solns.pdf) -- **solutions** 
-->

---

**Class 23: March 6th, 2026**<br>
Estimators. Bias.<br>

<!--
[Class notes](notes/m378k-mar-07-2025.pdf)
-->

---

**Class 24: March 9th, 2026**<br>
Mean squared error.<br>

[Problem Set #15](problem-sets/m378k-ps15-bias-mse-probs.pdf):  **Problems we will work on in class**

<!--
[Class notes](notes/m378k-oct-31-2025.pdf)

[Homework #7](hw/m378k-hw7-gamma-solns.pdf) -- **solutions**

[Homework #8](hw/m378k-hw8-statistics-probs.pdf) -- **due on Friday, November 7th, 2025**
-->

---

**Class 25: March 11th, 2026**<br>
<span style="color: red;">**In-Term Two**</span><br>

<!--
[In-Term Two](exams/m378k-two-solns.pdf) -- **solutions** 
-->

---

**Class 26: March 13th, 2026**<br>
More on MSE.<br>

<!--
[Class notes](notes/m378k-nov-03-2025.pdf)

[Problem Set #15](problem-sets/m378k-ps15-bias-mse-solns.pdf):  **solutions**

[Homework #9](hw/m378k-hw9-goodness-probs.pdf) -- **due on Friday, November 14th, 2025**
-->

---

**Class 27: March 23rd, 2026**<br>
Confidence intervals.<br>

<!--
[Class notes](notes/m378k-nov-05-2025.pdf)
-->

---

**Class 28: March 25th, 2026**<br>
More on confidence intervals.<br>

[Problem Set #16](problem-sets/m378k-ps16-conf-int-probs.pdf):  **Problems we will work on in class**

<!--
[Class notes](notes/m378k-nov-07-2025.pdf)

[Homework #8](hw/m378k-hw8-statistics-solns.pdf) -- **solutions**
-->

---

**Class 29: March 27th, 2026**<br>
Approximate confidence intervals for the population proportion. <br>

<!--
[Class notes](notes/m378k-nov-10-2025.pdf)
-->

---

**Class 30: March 30th, 2026**<br>
Confidence intervals for the variance.<br>

<!--
[Class notes](notes/m378k-nov-12-2025.pdf)
-->

---

**Class 31: April 1st, 2026**<br>
Confidence intervals for the mean with the variance unknown.<br>

[Wikipedia](https://en.wikipedia.org/wiki/William_Sealy_Gosset): William Sealy Gosset 

[Mathematica demonstration](http://demonstrations.wolfram.com/StudentsTDistribution/): The Student's t-distribution 

[t-table](notes/t-table.pdf)

<!--
[Class notes](notes/m378k-nov-14-2025.pdf)

[Problem Set #16](problem-sets/m378k-ps16-conf-int-solns.pdf):  **Solutions**

[Homework #9](hw/m378k-hw9-goodness-solns.pdf) -- **solutions**

[Homework #10](hw/m378k-hw10-umvue-conf-int-probs.pdf) -- **due on Friday, November 21st, 2025**
-->

---

**Class 32: April 3rd, 2026**<br>
Relative efficiency.<br>

[Problem Set #17](problem-sets/m378k-ps17-rel-eff-probs.pdf):  **Problems we will work on in class**

<!--
[Problem Set #17](problem-sets/m378k-ps17-rel-eff-solns.pdf):  **Solutions**
-->


---

**Class 33: April 6th, 2026**<br>
Consistency.<br>

[`R`-code](code/frequencies.R)

[Problem Set #18](problem-sets/m378k-ps18-consistency-probs.pdf):  **Problems we will work on in class**

<!--
[Problem Set #18](problem-sets/m378k-ps18-consistency-solns.pdf):  **Solutions**

[Class notes](notes/m378k-apr-04-2025.pdf)

[Homework #10](hw/m378k-hw10-conf-int-rel-eff-probs.pdf) -- **due on Friday, April 18th, 2025**
-->

Likelihood.<br>

---

**Class 34: April 8th, 2026**<br>
Maximum Likelihood Estimators.<br>

<!--
[Class notes](notes/m378k-nov-17-2025.pdf)

[Class notes](notes/m378k-nov-19-2025.pdf)

[Class notes](notes/m378k-nov-21-2025.pdf)
-->

---

**Class 35: April 10th, 2026**<br>
Sufficient statistics.<br>

<!--
[Class notes](notes/m378k-apr-11-2025.pdf)

[Homework #9](hw/m378k-hw9-umvue-conf-int-solns.pdf) -- **solutions**
-->

---

**Class 36: April 13th, 2026**<br>
More on sufficient statistics. 

<!--
[Class notes](notes/m378k-apr-14-2025.pdf)
-->

---

**Class 37: April 15th, 2026**<br>
Hypothesis testing.<br>

<!--
[Class notes](notes/m378k-apr-16-2025.pdf)

[In-Term Three](exams/m378k-three-topics.pdf): Topics

[Practice for In-Term Three](exams/m378k-three-sample-probs.pdf): Problems

[Practice for In-Term Three](exams/m378k-three-sample-solns.pdf): Solutions

[Homework #10](hw/m378k-hw10-umvue-conf-int-solns.pdf) -- **solutions**
-->

---

**Class 38: April 17th, 2026**<br>
Hypothesis tests for the mean.<br>

<!--
[Class notes](notes/m378k-dec-01-2025.pdf)
-->

---

**Class 39: April 20th, 2026**<br>
Hypothesis testing practice.<br>

[Problem Set #19](problem-sets/m378k-ps19-hypothesis-testing-probs.pdf):  **Problems we will work on in class**

<!--
[Class notes](notes/m378k-dec-05-2025.pdf)

[Problem Set #19](problem-sets/m378k-ps19-hypothesis-testing-solns.pdf):  **Solutions**

[Homework #10](hw/m378k-hw10-conf-int-rel-eff-solns.pdf) -- **solutions**

[`R` code on hypothesis testing](code/single-hypothesis.R)
-->

---

**Class 40: April 22nd, 2026**<br>
<span style="color: red;">**In-Term Three**</span><br>

<!--
[In-Term Three](exams/m378k-three-solns.pdf) -- **solutions**
-->

---

**Class 41: April 24th, 2026**<br>
The Bayesian approach.<br>

<!--
[Class notes](notes/m378k-apr-21-2025.pdf)
-->

---

**Class 42: April 27th, 2026**<br>
More on the Bayesian approach.<br>

<!--
[Class notes](notes/m378k-apr-25-2025.pdf)


Problem-solving session.<br>

[Class notes](notes/m378k-dec-08-2025.pdf)

---

[Practice for the Final Exam](exams/m378k-final-sample-probs.pdf) -- **problems** 

[Practice for the Final Exam](exams/m378k-final-sample-solns.pdf) -- **solutions** 
-->
