---
title: "Project #4: Put-call parity. More Monte Carlo. The normal approximation to the binomial."
author: "Milica Cudina"
date: "`r Sys.Date()`"
output: pdf_document
urlcolor: blue
---
<!-- The author of this template is Dr. Gordan Zitkovic.-->
<!-- The code chunk below contains some settings that will  -->
<!-- make your R code look better in the output pdf file.  -->
<!-- If you are curious about what each option below does, -->
<!-- go to https://yihui.org/knitr/options/ -->
<!-- If not, feel free to disregard everything ...  -->
```{r echo=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.align="center",
  fig.pos="t",
  strip.white = TRUE
)
```
<!-- ... down to here. -->

---

## Problem #1 (25 points)
### Put-call parity
**(5 points)**
Using put-call parity, find the formula for the interest rate if all other ingredients are known. 

**(5 points)** 
Based on the above, what can you say about the interest rates $r$ you expect to obtain for varying values of the strike price?

**(10 points)**
Based on the data set "apple-parity.csv", calculate the continuously compounded, risk-free interest rate for all the strike prices given. Be careful about how you use the *bid* and *ask/offer* prices of the options. Set $T=0.25$. Plot the values of the interest rate you obtain as they depend on the strike prices. 

**(5 points)**
What do you notice about the above plot? Does it or does it not agree with your prediction from the second question in the problem? Substantiate your answer. 

## Problem #2 (25 points)
To what do you attribute the discrepancies you observed in the previous problem? Think about it a bit. Then, if you don't have any ideas look at the paper by *Brenner* and *Galai* uploaded into Canvas (under *Files* in the folder *articles*). 

## Problem #3 (15 points)
Let the continuously compounded, risk-free interest rate be $0.05$. 

Consider a stock whose current price is \$80 and whose volatility is $0.2$. We will be pricing a variety of options using a *forward binomial tree*. 

**(5 points)** 
Price a one-year, \$85-strike European call option analytically using a $100-$period binomial tree. 

**(5 points)** 
Price a one-year, \$85-strike European call option using *Monte Carlo* with 10000 simulations with a $100-$period binomial tree. 

**(5 points)** 
Price a half-year, \$78-strike European put option analytically using a $100-$period binomial tree. 

**(5 points)** 
Price a half-year, \$78-strike European put option using *Monte Carlo* with 10000 simulations with a $100-$period binomial tree. 

**(5 points)** 
Comment on the accuracy of the *Monte Carlo* method. Which theorem from probability is useful here?

## Problem #4 (25 points)
Let $\{X_n, n = 1, 2, \dots\}$ be a sequence of random variables such that 
$$X_n \sim Binomial(n, p)$$ where $p$ is a constant between $0$ and $1$. 

**(5 points)** 
State the *DeMoivre-Laplace Theorem* (aka the *normal approximation to the binomial*) in the context of the above sequence of random variables. 

**(5 points)**
Let $p=0.78$. For $n=1000$, plot the **theoretical** histogram of $X_n$. Superimpose the appropriate density of the normal distribution on that histogram (according to the theorem referenced above). 

**(5 points)** 
Let $p=0.42$. 
For $n=1000$, draw $10000$ simulated values of $X_n$ and plot the histogram of the draws. Superimpose the appropriate density of the normal distribution on that histogram (according to the theorem referenced above). 

## Problem #5 (10 points)
Let $\{Y_n, n = 1, 2, \dots\}$ be a sequence of random variables such that 
$$Y_n \sim Binomial(n, p_n)$$ where $p_n$ is given by
$$p_n=\frac{1}{1+e^{0.25\sqrt{1/n}}}$$.

For $n=100, 1000, 5000, 10000$, draw $10000$ simulated values of $Y_n$ and plot the histogram of the draws. Does the theorem referenced in the previous problem apply to this situation or not? Substantiate your answer. 


