---
title: "Project #5: More Monte Carlo. More on portfolios. Lognormal stock prices."
author: "Milica Cudina"
date: "`r Sys.Date()`"
output: pdf_document
urlcolor: blue
---
<!-- The author of this template is Dr. Gordan Zitkovic.-->
<!-- The code chunk below contains some settings that will  -->
<!-- make your R code look better in the output pdf file.  -->
<!-- If you are curious about what each option below does, -->
<!-- go to https://yihui.org/knitr/options/ -->
<!-- If not, feel free to disregard everything ...  -->
```{r echo=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.align="center",
  fig.pos="t",
  strip.white = TRUE
)
```
<!-- ... down to here. -->

---

## Problem #1 (25 points)
Your initial wealth is exactly \$100. You are allowed to invest in
shares of a particular stock. You are also allowed to both lend and
borrow at the continuously compounded risk-free interest rate of
0.05. Keeping your money uninvested is **not allowed**.

You can rebalance your portfolio every morning, once you have observed
the opening stock price. This means that you can change the number of
shares you own (if you decide to do so) and accordingly adapt your
risk-free investment.

You proceed to create a ``rule'' according to which you will be
rebalancing your portfolio. Here is a possible rule you can use:

*I start by investing in one share of stoch. Then, every day I will flip a fair coin. If the outcome is heads, I will buy one share of stock. If the outcome is tails, I will
  short one share. The balance of my wealth is to be invested at the
  risk-free rate (if needed, I will borrow at the continuously
  compounded risk-free interest rate).*

Over the following 10 days, you observe the following stock prices for a non-dividend-paying stock:

\medskip

\begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|c|}
\hline
{\bf Day} & 0 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 \\
\hline
{\bf Stock price} &100 & 80 & 64 & 80 & 64 & 80 & 100 & 80 & 64 & 80 & 100 \\
\hline
\end{tabular}

\medskip

As the time passes you follow investment rules above to rebalance your portfolio. Complete the following table describing your portfolio \textbf{just before and just after} the rebalancing is done. 
Even more precisely, for the $10$ days, both for "morning" and "evening" print out:

* the number of shares of stock in the portfolio, 
* the balance of the risk-free investment, 
* the wealth in the stock, 
* the total wealth. 

## Problem #2 (25 points)
Repeat the above problem, but with a new investment ``rule'' of your own. You can use the above rule or any of the rules you encountered in previous projects for inspiration, but do not just merely make simple (trivial!) adjustments.

## Problem #3 (25 points)
Let the continuously compounded, risk-free interest rate be $0.05$. 

Consider a stock whose current price is \$80 and whose volatility is $0.2$. We will be pricing a variety of options using a *forward binomial tree*. 

**(5 points)** 
Price a one-year, \$85-strike European call option analytically using a $100-$period binomial tree. 

**(5 points)** 
Price a one-year, \$85-strike European call option using *Monte Carlo* with 10000 simulations with a $100-$period binomial tree. 

**(5 points)** 
Price a half-year, \$78-strike European put option analytically using a $100-$period binomial tree. 

**(5 points)** 
Price a half-year, \$78-strike European put option using *Monte Carlo* with 10000 simulations with a $100-$period binomial tree. 

**(5 points)** 
Comment on the accuracy of the *Monte Carlo* method. Which theorem from probability is useful here?

## Problem #4 (25 points)
Assume the **Black-Scholes model**.
The continuously compounded, risk-free interest rate is $0.06.$ Let the current stock price of a non-dividend-paying stock be \$100. Let its volatility be $0.25$. 

**(5 points)** 
Simulate 1000 values of the stock price at time $t=3$. 
Draw a histogram of the obtained set of values.  

**(6 points)** 
Superimpose the graph of the density of a lognormal distribution of $S(3)$ with the appropriate parameters onto the histogram obtained above. The command `dlnorm` should come in handy.  

**(2 points)** 
Find the median of the set of simulated values you obtained above.

**(2 points)** 
Find the mean of the set of simulated values you obtained above.

**(2 points)**
What is the proportion of stock prices you 
created in this way that above \$105? 

**(5 points)** 
What is the theoretical risk-neutral probability that the final asset price exceeds \$105?

**(3 points)** 
Comment on the comparison between the proportion and the risk-neutral probability you obtained above. Which theorem from probability is useful here?

