---
title: "Probability Models with Actuarial Applications (M339J/M389J)"
output: html_document
---
<style>
  hr {
      position: relative; 
            top: 20px; 
            border: none; 
            height: 2px; 
            background: black; 
            margin-bottom: 50px; 
  }
</style>

---

**Important external links**

[Cornell Notes](http://lsc.cornell.edu/how-to-study/taking-notes/cornell-note-taking-system/)

A MOOC: [Intro to Actuarial Science](https://www.edx.org/course/introduction-actuarial-science-anux-anu-actuarialx-1)

[The FAM Exam
curriculum](https://www.soa.org/48dfc7/globalassets/assets/files/edu/2023/2023-03-exam-fam-syllabus.pdf)

[The FAM-S Exam
tables](https://www.soa.org/globalassets/assets/files/edu/2022/tables-fam-s.pdf)

Link to the [Sample SoA problems for
FAM-S](https://www.soa.org/globalassets/assets/files/edu/2022/fam-s-sample-questions.pdf)

Link to the [Sample SoA solutions for
FAM-S](https://www.soa.org/globalassets/assets/files/edu/2022/fam-s-sample-solutions.pdf)

Our open-source textbook: [Loss Data Analytics](https://openacttexts.github.io/Loss-Data-Analytics/)

Our open-source short course: [Loss data short course](https://openacttexts.github.io/LDACourse1/)

---

**Lecture notes and the like**

[Materials on R](https://mcudina.github.io/rbook/)

---

**On R and RStudio**

`R` will be used extensively in this course. Quizzes will also (partially) be required to be completed in `R`. I created some resources for *Applied Statistics*. They are linked here: 

[R (main website)](https://www.r-project.org/)

[RStudio (main website)](https://rstudio.com/)

[The instructions slideshow](instructions/m358k-R-instructions.html)

[The basic R slideshow](instructions/m358k-basic-R.html)

[The basic R "cheatsheet"](https://raw.githubusercontent.com/rstudio/cheatsheets/master/base-r.pdf)

[If ... else](https://www.datamentor.io/r-programming/if-else-statement/)

[A tutorial on functions in R](https://www.tutorialspoint.com/r/r_functions.htm)

---

**Class 1: January 9th**<br>
Orientation.<br>

[A role model](pics/bilbo.jpeg)

[First-Day Handout](syllabus/syllabus-54730.pdf) -- 11am 

[First-Day Handout](syllabus/syllabus-54735.pdf) -- 1pm 

[Day-by-day](notes/m339j-spring-2023-todo.pdf)

Modeling.<br>

Slides: [Actuarial Sims.](slides/m339j-sims.pdf)

[SIAM Videos on Mathematical Modeling](https://youtube.com/playlist?list=PLf_ipOSbWC87nFTi6MaB4begv56yPKsOJ)

[Quiz #1](quizzes/m339j-quiz-one-probability.pdf) -- **due on Wednesday, January 18th**

[Homework #1](hw/m339j-hw1.pdf) -- **due on Friday, January 20th**

---

**Class 2: January 11th**<br>
Cumulative distribution function. Survival function.<br> 

[Class notes](notes/m339j-jan-11-2023.pdf): Probability review: Random variables. 

[Lecture notes](lectures/m339j-lecture1-cdf.pdf): The cumulative distribution function and friends

[Problem Set #1](problem-sets/m339j-ps1-cdf.pdf) -- **problems**

[Problem Set #1](problem-sets/m339j-ps1-cdf-solns.pdf) -- **solutions**

---

**Class 3: January 13th**<br>
Percentiles. Value-at-Risk. <span style="color: purple;">**(Sections 3.1.2, 4.1.1.3, 10.3.2)**</span> <br>

[Wikipedia](https://en.wikipedia.org/wiki/Value_at_risk): Value at Risk (VaR). 

Discrete random variables. Probability mass function. <br>

[Lecture notes](lectures/m339j-lecture2-types.pdf): Types of random variables.

[Class notes](notes/m339j-jan-13-2023.pdf): pmf. 

---

**Class 4: January 18th**<br>
Continuous random variables. Probability density function. Mixed random variables.<br>

[Class notes](notes/m339j-jan-18-2023.pdf): pdf. Mixed r.v.s 

[Quiz #1](quizzes/m339j-quiz-one-probability-solns.pdf) -- **solutions**

[Quiz #2](quizzes/m339j-quiz2-cdf.pdf) -- **due on Wednesday, January 25th**

---

**Class 5: January 20th**<br>
The exponential distribution.<br>

[Lecture notes](lectures/m339j-lecture3-exponential.pdf): The exponential distribution.

[Wikipedia](https://en.wikipedia.org/wiki/Exponential_distribution): The exponential distribution.

[Problem Set #2](problem-sets/m339j-ps2-exponential.pdf) -- **problems**

[Class notes](notes/m339j-jan-20-2023.pdf): Independent r.v.s. The exponential distribution.  

[Problem Set #2](problem-sets/m339j-ps2-exponential-solns.pdf) -- **solutions**

[Quiz #3](quizzes/m339j-quiz3-pdf-pmf.pdf) -- **due on Wednesday, February 1st**

[Quiz #4](quizzes/m339j-quiz4-exponential.pdf) -- **due on Wednesday, February 15th**

[Homework #1](hw/m339j-hw1-solns.pdf) -- **solutions**

[Homework #2](hw/m339j-hw2.pdf) -- **due on Friday, January 27th**

---

**Class 6: January 23rd**<br>
Random number generation. The inverse transform method <span style="color: purple;">**(Section 6.1.2)**</span>.<br>

[Wikipedia](https://en.wikipedia.org/wiki/Random_number_generation): Random number generation

[Wikipedia](https://en.wikipedia.org/wiki/Mersenne_Twister): Mersenne twister

[An atmospheric RNG](https://www.random.org/)

[Lecture notes](lectures/m339j-lecture4-inv-trans.pdf): The inverse transform method.

[Lecture notes with proofs](lectures/m339j-lecture4-inv-trans-w-pfs.pdf): The inverse transform method.

[Class notes](notes/m339j-jan-23-2023.pdf): The inverse transform method.

[Quiz #5](quizzes/m339j-quiz5-inv-trans.pdf) -- **due on Wednesday, February 22nd**

Basics of `R`. <br>

[The console printout](notes/console.txt)

[Quiz #6](quizzes/m339j-quiz6-r.pdf) -- **due on Wednesday, March 1st**

[Quiz #7](quizzes/m339j-quiz7-r-basics.pdf) -- **due on Wednesday, March 8th**

[Quiz #7](code/m339j-quiz7-r-basics.Rmd) -- **this is the Rmd file you can use to simply insert `R`-chunks with your answers**

---

**Class 7: January 25th**<br>
`R` scripts and `R` notebooks. `For` loops.<br>

[The console printout](notes/console-contd.txt)

Functions in `R`. `If ... else` in `R`. Simulations of random variables. <br> 

[The R-script from class](code/first-script-1pm.R): For loops. Functions. If else.

[The R-script from class](code/expon-1pm.R): The exponential distribution.

[Quiz #2](quizzes/m339j-quiz2-cdf-solns.pdf) -- **solutions**

[Quiz #8](quizzes/m339j-quiz8-r-simulations.pdf) -- **due on Wednesday, March 22nd**

[Quiz #8](code/m339j-quiz8-r-simulations.Rmd) -- **this is the Rmd file you can use to simply insert `R`-chunks with your answers**

[Quiz #9](quizzes/m339j-quiz9-r-pareto-itm.pdf) -- **due on Wednesday, March 29th**

[Quiz #9](code/m339j-quiz9-r-pareto-itm.Rmd) -- **this is the Rmd file you can use to simply insert `R`-chunks with your answers**

---

**Class 8: January 27th**<br>
Focus on the expectation <span style="color: purple;">**(Section 3.1.1)**</span>. The tail formula for the expectation. <br>

[Class notes](notes/m339j-jan-27-2023.pdf): The expected value.  

[Problem Set #3](problem-sets/m339j-ps3-expectation.pdf) -- **problems**

[Problem Set #3](problem-sets/m339j-ps3-expectation-solns.pdf) -- **solutions**

[Homework #2](hw/m339j-hw2-solns.pdf) -- **solutions**

[Homework #3](hw/m339j-hw3.pdf) -- **due on Friday, February 10th, 2023**

---

**Class 9: January 30th**<br>
TVaR <span style="color: purple;">**(Section 10.3.3)**</span>. Strong Law of Large Numbers. <br>

[Class notes](notes/m339j-jan-30-2023.pdf): The tail formula for the expectation. SLLN.  

---

**Class 10: February 1st**<br>
<span style="color: blue;">**Asynchronous work due to winter conditions.**</span>
<br>

Monte Carlo simulation. Basics of the binomial distribution.<br>

[Wikipedia](https://en.wikipedia.org/wiki/Monte_Carlo_method): The Monte Carlo method. 

[The R-script from class](code/monte-carlo-in-class.R)

Moments. Variance. Coefficient of variation <span style="color: purple;">**(Section 3.1.1)**</span>
<br>

[Class notes](notes/m339j-moments.pdf): Moments. Variance. Coefficient of variation. 

---

**Class 11: February 3rd**<br>
<span style="color: blue;">**Asynchronous work due to winter conditions.**</span><br>

[Problem Set #4](problem-sets/m339j-ps4-winter-expectation.pdf) -- **problems**

[Problem Set #4](problem-sets/m339j-ps4-winter-expectation-solns.pdf) -- **solutions**

---

**Class 12: February 6th**<br>
The excess loss random variable. Per-payment and per-loss random variables <span style="color: purple;">**(Section 3.4.1)**</span>. <br>

[Class notes](notes/m339j-feb-06-2023.pdf): Per payment and per loss random variables. 

[Problem](problem-sets/stam-sample-p168.pdf)

**Suggested textbook examples:** <span style="color: purple;">**3.4.1, 3.4.2**</span>

[Homework #4](hw/m339j-hw4.pdf) -- **due on Friday, February 17th, 2023**

---

**Class 13: February 8th**<br>
More on the per-payment and per-loss random variables. The limited loss random variable.<br>

[Problem packet](problem-sets/m339j-deductible.pdf)

[Class notes](notes/m339j-feb-08-2023.pdf): More on the per-payment and per-loss random variables. The limited loss random variable.

[Quiz #3](quizzes/m339j-quiz3-pdf-pmf-solns.pdf) -- **solutions**

[In-Term One](exams/m339j-one-topics.pdf): Topics

[Practice for In-Term One](exams/m339j-one-sample-probs.pdf) -- **problems** 

[Practice for In-Term One](exams/m339j-one-sample-solns.pdf) -- **solutions** 

---

**Class 14: February 10th**<br>
Loss-modifications demonstration. 

[Class notes](notes/m339j-feb-10-2023.pdf): Even more on the per-payment and per-loss random variables. The limited loss random variable.

[The R-notebook from class](code/loss-modifications.Rmd)

[More Practice for In-Term One](exams/m339j-one-sample-extra-probs.pdf) -- **problems** 

[More Practice for In-Term One](exams/m339j-one-sample-extra-solns.pdf) -- **solutions** 

[Homework #3](hw/m339j-hw3-solns.pdf) -- **solutions**

---

**Class 15: February 13th**<br>
<span style="color: red;">**In-Term One**</span><br>

[In-Term One](exams/m339j-one-solns.pdf) -- **solutions** 

---

**Class 16: February 15th**<br>
Franchise deductibles <span style="color: purple;">**(Sections 3.4.1)**</span>.

Slides: [Types of deductibles.](slides/m339j-all-deductibles.pdf)

Loss elimination ratio <span style="color: purple;">**(Section 3.4.1)**</span>. <br>

Other loss modifications (combined) <span style="color: purple;">**(Section 3.4.2, 3.4.3)**</span>.<br>

[Short course videos](https://openacttexts.github.io/LDACourse1/modeling-loss-severity.html#coverage-modifications)

[Quiz #4](quizzes/m339j-quiz4-exponential-solns.pdf) -- **solutions**

---

**Class 17: February 17th**<br>
Scale distributions. <span style="color: purple;">**(Section 3.3.2)**</span> 

Slides: [Scale distributions.](slides/m339j-scale.pdf)

[Homework #5](hw/m339j-hw5.pdf) -- **due on Friday, February 24th, 2023**

More on loss modifications (combined) <span style="color: purple;">**(Section 3.4.2, 3.4.3)**</span>.<br>

[Problem packet](problem-sets/m339j-ler-inflation.pdf)

[Class notes](notes/m339j-feb-17-2023.pdf): Parametric distributions. Scale distributions. Loss elimination ratio.

**Suggested textbook examples:** <span style="color: purple;">**3.4.3, 3.4.4, 3.4.5**</span>

[Quiz #10](quizzes/m339j-quiz10-loss-mods.pdf) -- **due on Wednesday, April 5th**

[Homework #4](hw/m339j-hw4-solns.pdf) -- **solutions**

---

**Class 18: February 20th**<br>
Even more on loss modifications. <br>

[Problem Set #5](problem-sets/m339j-ps5-policy-mods.pdf) -- **problems**

[Class notes](notes/m339j-feb-20-2023.pdf): More policy modifications.

[Problem Set #5](problem-sets/m339j-ps5-policy-mods-solns.pdf) -- **solutions**

---

**Class 19: February 22nd**<br>
Proportional and excess of loss reinsurance <span style="color: purple;">**(Sections 3.4.4, 10.4)**</span>. 

[Problem packet](problem-sets/m339j-reinsurance.pdf)

[Class notes](notes/m339j-feb-22-2023.pdf): More on policy modifications. Reinsurance.

[Homework #6](hw/m339j-hw6.pdf) -- **due on Friday, March 3rd**

mgf and pgf. Sums of independent random
variables. <span style="color: purple;">**(Sections 3.1.2, 3.1.3)**</span>. Central Limit Theorem.<br>

[Lecture notes](lectures/m339j-lecture5-mgf-pgf.pdf): Generating functions.

[Lecture notes](lectures/m339j-lecture6-clt.pdf): The Central Limit Theorem.

**Suggested textbook examples:** <span style="color: purple;">**3.1.1, 3.1.3, 3.1.4**</span>

[Quiz #5](quizzes/m339j-quiz5-inv-trans-solns.pdf) -- **solutions**

---

**Class 20: February 24th**<br>
The Poisson distribution <span style="color: purple;">**(Section 2.2.3.2)**</span>.<br>

[Problem packet](problem-sets/m339j-poisson.pdf)

[Class notes](notes/m339j-feb-24-2023.pdf): More on reinsurance. The Poisson distribution.

[Homework #5](hw/m339j-hw5-solns.pdf) -- **solutions**

---

**Class 21: February 27th**<br>
Poisson distribution practice.<br>

[Class notes](notes/m339j-feb-27-2023.pdf): More on the Poisson distribution.

---

**Class 22: March 1st**<br>
Poisson thinning. The negative binomial distribution <span style="color: purple;">**(Section 2.2.3.3)**</span>.<br>

[Class notes](notes/m339j-mar-01-2023.pdf): Poisson thinning. The negative binomial distribution.

Slides: [The negative binomial distribution.](slides/NegBinDistn.pdf)

[Quiz #11](quizzes/m339j-quiz11-poisson.pdf) -- **due on Wednesday, April 12th**

---

**Class 23: March 3rd**<br>
The binomial distribution <span style="color: purple;">**(Section 2.2.3.1)**</span>. The binomial-Poisson connection.<br> 

[Problem packet](problem-sets/m339j-binomial-a-b-0.pdf)

[Class notes](notes/m339j-mar-03-2023.pdf): The binomial distribution. 

**Suggested problem**: Sample FAM-S Problem #25

[Homework #6](hw/m339j-hw6-solns.pdf) -- **solutions**

[Quiz #12](quizzes/m339j-quiz12-discrete.pdf) -- **due on Wednesday, April 19th**

---

**Class 24: March 6th**<br>
The $(a, b, 0)$ class <span style="color: purple;">**(Section 2.3)**</span>. The $(a, b, 1)$ class <span style="color: purple;">**(Section 2.5)**</span>. On compounding.<br>

[Class notes](notes/m339j-mar-06-2023.pdf): $(a, b, 0)-$class practice. On compounding. 

**Suggested textbook example:** <span style="color: purple;">**5.5.2, 5.5.3**</span>

[Homework #7](hw/m339j-hw7.pdf) -- **due on Friday, March 10th**

<!--
[Quiz #13](quizzes/m339j-quiz13-compound-example.pdf) -- **due on Thursday, April 28th for extra credit**
-->

---

**Class 25: March 8th**<br>
The impact of deductibles on claim frequency <span style="color: purple;">**(Section 5.5.2)**</span>.<br> 
 
[Problem packet](problem-sets/m339j-freq-ded.pdf)

The individual risk model <span style="color: purple;">**(Sections 5.2 and 5.3)**</span>.<br> 

[Class notes](notes/m339j-mar-08-2023.pdf): The impact of deductibles on claim frequency. The individual risk model. 

<!--
[Quiz #16](quizzes/m339j-quiz16-discrete-solns.pdf) -- **solutions**
-->

Monte Carlo for the individual risk model.<br> 

[R-script](code/monte-carlo-individual-risk.R)

[Quiz #7](quizzes/m339j-quiz7-r-basics-solns.pdf) -- **solutions**

---

**Class 26: March 10th**<br>
The collective risk model.<br> 

[Problem packet](problem-sets/m339j-agg-loss.pdf)

[Class notes](notes/m339j-mar-10-2023.pdf): The collective risk model. 

[Homework #7](hw/m339j-hw7-solns.pdf) -- **solutions**

[In-Term Two](exams/m339j-two-topics.pdf): Topics

[Practice for In-Term Two](exams/m339j-two-sample-probs.pdf): **problems**

[Practice for In-Term Two](exams/m339j-two-sample-solns.pdf): **solutions**

---

**Class 27: March 20th**<br>
Monte Carlo for the collective risk model.<br> 

[The R-notebook from class](code/monte-carlo-collective.Rmd)

[The R-script from class](code/errors-pic.R)

Stop-loss insurance <span style="color: purple;">**(Section 5.3.2)**</span>. 

[Class notes](notes/m339j-mar-20-2023.pdf): The collective risk model [cont'd]. 

[Homework #8](hw/m339j-hw8.pdf) -- **due on Friday, March 24th**

---

**Class 28: March 22nd**<br>
Compound Poisson <span style="color: purple;">**(Section 5.3.1: Special case)**</span>.<br>

[Problem packet](problem-sets/m339j-compound-poisson.pdf)

[Problem](problem-sets/m339j-stam-p125.pdf)

[Problem](problem-sets/m339j-compound-poisson-individual.pdf)

[Class notes](notes/m339j-mar-22-2023.pdf): Compound Poissons.

[Quiz #8](quizzes/m339j-quiz8-r-simulations-solns.pdf) -- **solutions**

---

**Class 29: March 24th**<br>
More on the stop-loss insurance <span style="color: purple;">**(Section 5.3.2)**</span>. The interpolation theorem.<br>

[Problem](problem-sets/m339j-stop-loss.pdf): Stop loss. 

[Problem](problem-sets/m339j-interpolation-thm.pdf): The interpolation theorem.

[Class notes](notes/m339j-mar-24-2023.pdf): The net stop-loss premium. The interpolation theorem.

[Homework #8](hw/m339j-hw8-solns.pdf) -- **solutions**

[Homework #9](hw/m339j-hw9.pdf) -- **due on Friday, March 31st**

**(asynchronous content)** The recursive formula for the distribution of aggregate losses <span style="color: purple;">**(Section 5.4.1)**</span>.<br>

[Problem packet](problem-sets/m339j-recursive.pdf)

[Class notes](notes/m339j-apr-20-2022.pdf): The recursive formula.

---

**Class 30: March 27th**<br>
<span style="color: red;">**In-Term Two**</span><br>

[In-Term Two](exams/m339j-two-solns.pdf): **Solutions** 

---

**Class 31: March 29th**<br>
Aggregate losses with an ordinary deductible per-loss.<br>

Slides: [Effect of individual deductibles](slides/m339j-effect-of-ded.pdf)

[Problem packet](problem-sets/m339j-agg-claims.pdf)

[Class notes](notes/m339j-mar-29-2023.pdf): Deductibles and counts.

[Quiz #9](quizzes/m339j-quiz9-r-pareto-itm-solns.pdf) -- **solutions**

[Homework #10](hw/m339j-hw10.pdf) -- **due on Friday, April 7th**

---

**Class 32: March 31st**<br>
Maximum-likelihood estimation: First principles. Individual unmodified data.<br>

Slides: [Maximum likelihood estimation.](slides/m339j-mle.pdf)

[Problem packet](problem-sets/m339j-mle.pdf)

[Class notes](notes/m339j-mar-31-2023.pdf): MLE

[Homework #9](hw/m339j-hw9-solns.pdf) -- **solutions**

[Homework #11](hw/m339j-hw11.pdf) -- **due on Friday, April 14th**

---

**Class 33: April 3rd**<br>
Maximum-likelihood estimation: Grouped data.<br>

[Problem packet](problem-sets/m339j-mle-grouped.pdf)

[Class notes](notes/m339j-apr-03-2023.pdf): MLE (grouped data). 

---

**Class 34: April 5th**<br>
Maximum-likelihood estimation: Truncation and censoring.<br>

[Problem packet](problem-sets/m339j-mle-censoring-truncation.pdf)

[Class notes](notes/m339j-apr-05-2023.pdf): MLE (censoring and truncation). 

[Quiz #10](quizzes/m339j-quiz10-loss-mods-solns.pdf) -- **solutions**

---

**Class 35: April 7th**<br>
Maximum-likelihood estimation: More on truncation.<br>

[Class notes](notes/m339j-apr-07-2023.pdf): MLE (truncation practice). 

[Homework #10](hw/m339j-hw10-solns.pdf) -- **solutions**

---

**Class 36: April 10th**<br>
Maximum-likelihood estimation: Bernoulli and Poisson.<br>

[Problem packet](problem-sets/m339j-mle-poisson.pdf)

<!--
[Class notes](notes/m339j-may-06-2022.pdf): MLE (Bernoulli and Poisson). 
-->

Maximum-likelihood estimation: Negative binomial and binomial.<br>

---

**Class 37: April 12th**<br>
Survival analysis.<br>

---

**Class 38: April 14th**<br>
Maximum-likelihood estimation for mortality.<br>

---

**Class 39: April 17th**<br>
Non-parametric estimation.<br>

---

**Class 40: April 19th**<br>
Kaplan-Meier.<br>

---

**Class 41: April 21st**<br>
Nelson-Aalen.<br>

---

**Class 42: April 24th**<br>
<span style="color: red;">**In-Term Three**</span><br>


<!--

Transformations <span style="color: purple;">**(Sections 3.3.3, 3.3.4)**</span>. 

[Class notes](notes/m339j-feb-23-2022.pdf): Multiplication by a constant. Raising a r.v. to a power. Exponentiation of a r.v. 

**Suggested textbook examples:** <span style="color: purple;">**3.3.1, 3.3.2, 3.3.3, 3.3.4**</span>

[Quiz #11](quizzes/m339j-quiz11-transforms.pdf) -- **due on Friday, March 4th, 2022**

$k-$point mixtures <span style="color: purple;">**(Sections 3.3.5)**</span>.<br>

[Class notes](notes/m339j-feb-25-2022.pdf): $k-$point mixtures.

[The R-notebook from class](code/k-pt-mixtures.Rmd)

[Quiz #12](quizzes/m339j-quiz12-k-pt-mixture.pdf) -- **due on Monday, March 7th**

[Quiz #12](code/m339j-quiz12-k-pt-mixture.Rmd) -- **this is the Rmd file you can use to simply insert `R`-chunks with your answers**

Continuous mixtures <span style="color: purple;">**(Sections 3.3.6)**</span>.

[Class notes](notes/m339j-feb-28-2022.pdf): Continuous mixtures.

**Suggested textbook examples:** <span style="color: purple;">**3.3.5, 3.3.6, 3.3.7, 3.3.8**</span>

[Quiz #13](quizzes/m339j-quiz13-cont-mixture.pdf) -- **due on Friday, March 11th**

[Quiz #13](code/m339j-quiz13-cont-mixture.Rmd) -- **this is the Rmd file you can use to simply insert `R`-chunks with your answers**

Splicing.<br>   

[Problem packet](problem-sets/m339j-splicing-ord-ded.pdf)

[Class notes](notes/m339j-mar-02-2022.pdf): Splicing. Ordinary deductible (review).

**Suggested problems**: Sample STAM #168; Course 3 Exam (November 2000), Problem #21

[Quiz #11](quizzes/m339j-quiz11-transforms-solns.pdf) -- **solutions**

[Quiz #14](quizzes/m339j-quiz14-splicing-franchise.pdf) -- **due on Monday, March 21st**

[Quiz #12](quizzes/m339j-quiz12-k-pt-mixture-solns.pdf) -- **solutions**

[Quiz #13](quizzes/m339j-quiz13-cont-mixture-solns.pdf) -- **solutions**

[Quiz #14](quizzes/m339j-quiz14-splicing-franchise-solns.pdf) -- **solutions**

The Poisson-gamma mixture. 

[Proof of the claim from class](notes/m339j-poisson-gamma-proof.pdf): The Poisson-gamma mixture [proof].

**Suggested textbook example:** <span style="color: purple;">**2.6.2**</span>

**Suggested problems**: Sample STAM Problems #90, #105; Course 3 Exam (May 2000), Problem #4

[Quiz #15](quizzes/m339j-quiz15-poisson-solns.pdf) -- **solutions**

[In-Term Two](exams/m339j-two.pdf): **Problems** 

[In-Term Three](exams/m339j-three-topics.pdf): Topics

[Practice for In-Term Three](exams/m339j-three-sample-probs.pdf) --
**problems**

[Practice for In-Term Three](exams/m339j-three-sample-solns.pdf) -- **solutions**

[In-Term Three](exams/m339j-three.pdf) -- **due on Saturday, May 14th**

[In-Term Three](exams/m339j-three-solns.pdf) -- **solutions**

---


[Mock In-Term One](exams/m339j-one-mock-probs.pdf) -- **Problems** 

[Mock In-Term One](exams/m339j-one-mock-solns.pdf) -- **Solutions** 

---

[Mock In-Term Two](exams/m339j-two-mock.pdf): **Problems**

[Mock In-Term Two](exams/m339j-two-mock-solns.pdf): **Solutions**

[In-Term Three](exams/m339j-three-instructions.pdf): Instructions

[Mock In-Term Three](exams/m339j-three-mock-probs.pdf) --
**problems**

[Mock In-Term Three](exams/m339j-three-mock-solns.pdf) -- **solutions**

[Percentiles. Central Limit Theorem. mgf and pgf. Heavy
tails.](Lecture3_2and3_3and3_4.pdf)

Heavy tails. Risk measures.

More on scale distributions and k-point mixtures.

[Class notes](m339j-feb-12-2020.pdf): Scale distributions. k-point
mixtures.

Continuous models.

[Continuous models.](Lecture5_2.pdf)

[Mock In-Term Two](m339j-mock-two-probs.pdf) -- **Problems**

-->








